const typeName = 'SoftwareHouse.CrossFire.Common.Objects.TimeSpec';
const table = [
    {
        'January': false,
        'February': false,
        'March': false,
        'April': false,
        'May': false,
        'June': false,
        'July': false,
        'August': false,
        'September': false,
        'October': false,
        'November': false,
        'December': false,
        'ObjectID': 1,
        'Active': false,
        'DayOfMonth': null,
        'Description': '',
        'DurationTime': '00:00:00',
        'Enabled': true,
        'EndDateTime': '1970-01-01T00:00:00Z',
        'GUID': 'c0c27551-7a28-41cc-9345-046f722ba248',
        'IntervalTime': '00:00:00',
        'LastModifiedByID': 1,
        'LastModifiedTime': '2021-07-26T13:53:41.653Z',
        'Name': 'Never',
        'Protected': true,
        'StartDateTime': '2005-09-14T14:20:01.773',
        'ExpirationDateTime': '1970-01-01T00:00:00Z',
        'TimeZoneID': null,
        'OwnerID': null,
        'OwnerType': null,
        'Template': false,
        'DayOccurrence': 0,
        'Occurrence': 1,
        'Schedule': 1,
        'MonthsOfYear': null,
        'HolidayActive': false,
        'PartitionID': 1,
        'SpecialEditingRequired': true,
        'RecurrenceFrequency': 1,
        'ScheduleEndDateOption': 1,
        'ScheduleEndAfterOccurrence': 0,
        'HourlyScheduleType': 1,
        'RecurrencePatternType': 1,
        'ParentScheduleID': 0,
        'IsRandom': false,
        'YearlySchedule': false,
        'LocationMetaTagFullName': '',
        'ClassType': 'SoftwareHouse.CrossFire.Common.Objects.TimeSpec',
        '*routing': null,
        '*ObjectSize': 302,
        '*id': {
            '_values': [
                1
            ],
            '_objectTypeName': 'SoftwareHouse.CrossFire.Common.Objects.TimeSpec',
            '_appServer': 'VM-INGRTN-16-15',
            'Guid': 'c0c27551-7a28-41cc-9345-046f722ba248',
            'RoutingInfo': null,
            'ContextId': '00000000-0000-0000-0000-000000000000',
            'TransactionID': null
        },
        '*PK': [
            'ObjectID'
        ],
        '*state': 1,
        '*appServer': 'VM-INGRTN-16-15',
        '*context': '00000000-0000-0000-0000-000000000000',
        '*container': []
    },
    {
        'January': false,
        'February': false,
        'March': false,
        'April': false,
        'May': false,
        'June': false,
        'July': false,
        'August': false,
        'September': false,
        'October': false,
        'November': false,
        'December': false,
        'ObjectID': 2,
        'Active': true,
        'DayOfMonth': null,
        'Description': '',
        'DurationTime': '00:00:00',
        'Enabled': true,
        'EndDateTime': '1970-01-01T00:00:00Z',
        'GUID': 'f44bc47a-c7c7-440d-901b-f7d77a2586fe',
        'IntervalTime': '00:00:00',
        'LastModifiedByID': 1,
        'LastModifiedTime': '2021-07-26T13:53:41.653Z',
        'Name': 'Always',
        'Protected': true,
        'StartDateTime': '2005-09-14T14:30:17.213',
        'ExpirationDateTime': '1970-01-01T00:00:00Z',
        'TimeZoneID': null,
        'OwnerID': null,
        'OwnerType': null,
        'Template': false,
        'DayOccurrence': 0,
        'Occurrence': 1,
        'Schedule': 1,
        'MonthsOfYear': null,
        'HolidayActive': false,
        'PartitionID': 1,
        'SpecialEditingRequired': true,
        'RecurrenceFrequency': 1,
        'ScheduleEndDateOption': 1,
        'ScheduleEndAfterOccurrence': 0,
        'HourlyScheduleType': 1,
        'RecurrencePatternType': 1,
        'ParentScheduleID': 0,
        'IsRandom': false,
        'YearlySchedule': false,
        'LocationMetaTagFullName': '',
        'ClassType': 'SoftwareHouse.CrossFire.Common.Objects.TimeSpec',
        '*routing': null,
        '*ObjectSize': 303,
        '*id': {
            '_values': [
                2
            ],
            '_objectTypeName': 'SoftwareHouse.CrossFire.Common.Objects.TimeSpec',
            '_appServer': 'VM-INGRTN-16-15',
            'Guid': 'f44bc47a-c7c7-440d-901b-f7d77a2586fe',
            'RoutingInfo': null,
            'ContextId': '00000000-0000-0000-0000-000000000000',
            'TransactionID': null
        },
        '*PK': [
            'ObjectID'
        ],
        '*state': 1,
        '*appServer': 'VM-INGRTN-16-15',
        '*context': '00000000-0000-0000-0000-000000000000',
        '*container': [
            {
                'StartTimeAsDateTime': null,
                'EndTimeAsDateTime': null,
                'DurationAsString': null,
                'ProcessingOrder': null,
                'NumberOfChangesThisTransaction': null,
                'ObjectID': 1,
                'DurationTime': 864000000000,
                'Enabled': false,
                'Friday': true,
                'GUID': 'ada84ee0-aaf4-45fd-9796-8e614cc7311e',
                'HolidayGroupId': null,
                'LastModifiedByID': 1,
                'LastModifiedTime': '2021-07-26T13:53:48.11Z',
                'Monday': true,
                'Protected': true,
                'Saturday': true,
                'ScheduleID': 2,
                'StartTime': 0,
                'Sunday': true,
                'Thursday': true,
                'Tuesday': true,
                'Wednesday': true,
                'DefaultRecord': false,
                'Template': false,
                'ParentClassType': 'SoftwareHouse.CrossFire.Common.Objects.TimeSpec',
                'Variance': false,
                'VarianceStartDateTime': '1970-01-01T00:00:00Z',
                'VarianceEndDateTime': '1970-01-01T00:00:00Z',
                'OccurenceDeleted': false,
                'OriginalOccurenceStartDateTime': '1970-01-01T00:00:00Z',
                'OriginalOccurenceEndDateTime': '1970-01-01T00:00:00Z',
                'Description': null,
                'ClassType': 'SoftwareHouse.CrossFire.Common.Objects.TimeInterval',
                '*routing': null,
                '*ObjectSize': 348,
                '*id': {
                    '_values': [
                        1
                    ],
                    '_objectTypeName': 'SoftwareHouse.CrossFire.Common.Objects.TimeInterval',
                    '_appServer': 'VM-INGRTN-16-15',
                    'Guid': 'ada84ee0-aaf4-45fd-9796-8e614cc7311e',
                    'RoutingInfo': null,
                    'ContextId': '00000000-0000-0000-0000-000000000000',
                    'TransactionID': null
                },
                '*PK': [
                    'ObjectID'
                ],
                '*state': 1,
                '*appServer': 'VM-INGRTN-16-15',
                '*context': '00000000-0000-0000-0000-000000000000',
                '*container': []
            }
        ]
    },
    {
        'January': false,
        'February': false,
        'March': false,
        'April': false,
        'May': false,
        'June': false,
        'July': false,
        'August': false,
        'September': false,
        'October': false,
        'November': false,
        'December': false,
        'ObjectID': 3,
        'Active': false,
        'DayOfMonth': null,
        'Description': 'The built-in schedule for tasks that can be executed once per night: it starts at 2:17 AM and ends at 2:41 AM',
        'DurationTime': '00:00:00',
        'Enabled': true,
        'EndDateTime': '1970-01-01T00:00:00Z',
        'GUID': '7683d111-c60e-4b23-aa71-84de9d853583',
        'IntervalTime': '00:00:00',
        'LastModifiedByID': 1,
        'LastModifiedTime': '2021-07-26T13:53:41.653Z',
        'Name': 'Nightly',
        'Protected': true,
        'StartDateTime': '2005-09-14T14:20:01.773',
        'ExpirationDateTime': '1970-01-01T00:00:00Z',
        'TimeZoneID': null,
        'OwnerID': null,
        'OwnerType': null,
        'Template': false,
        'DayOccurrence': 0,
        'Occurrence': 1,
        'Schedule': 1,
        'MonthsOfYear': null,
        'HolidayActive': false,
        'PartitionID': 1,
        'SpecialEditingRequired': true,
        'RecurrenceFrequency': 1,
        'ScheduleEndDateOption': 1,
        'ScheduleEndAfterOccurrence': 0,
        'HourlyScheduleType': 1,
        'RecurrencePatternType': 1,
        'ParentScheduleID': 0,
        'IsRandom': false,
        'YearlySchedule': false,
        'LocationMetaTagFullName': '',
        'ClassType': 'SoftwareHouse.CrossFire.Common.Objects.TimeSpec',
        '*routing': null,
        '*ObjectSize': 413,
        '*id': {
            '_values': [
                3
            ],
            '_objectTypeName': 'SoftwareHouse.CrossFire.Common.Objects.TimeSpec',
            '_appServer': 'VM-INGRTN-16-15',
            'Guid': '7683d111-c60e-4b23-aa71-84de9d853583',
            'RoutingInfo': null,
            'ContextId': '00000000-0000-0000-0000-000000000000',
            'TransactionID': null
        },
        '*PK': [
            'ObjectID'
        ],
        '*state': 1,
        '*appServer': 'VM-INGRTN-16-15',
        '*context': '00000000-0000-0000-0000-000000000000',
        '*container': [
            {
                'StartTimeAsDateTime': null,
                'EndTimeAsDateTime': null,
                'DurationAsString': null,
                'ProcessingOrder': null,
                'NumberOfChangesThisTransaction': null,
                'ObjectID': 3,
                'DurationTime': 14400000000,
                'Enabled': false,
                'Friday': true,
                'GUID': 'd2d68b64-2f67-4c93-a65b-68c18eb23190',
                'HolidayGroupId': null,
                'LastModifiedByID': 1,
                'LastModifiedTime': '2021-07-26T13:53:48.11Z',
                'Monday': true,
                'Protected': true,
                'Saturday': true,
                'ScheduleID': 3,
                'StartTime': 82200000000,
                'Sunday': true,
                'Thursday': true,
                'Tuesday': true,
                'Wednesday': true,
                'DefaultRecord': false,
                'Template': false,
                'ParentClassType': 'SoftwareHouse.CrossFire.Common.Objects.TimeSpec',
                'Variance': false,
                'VarianceStartDateTime': '1970-01-01T00:00:00Z',
                'VarianceEndDateTime': '1970-01-01T00:00:00Z',
                'OccurenceDeleted': false,
                'OriginalOccurenceStartDateTime': '1970-01-01T00:00:00Z',
                'OriginalOccurenceEndDateTime': '1970-01-01T00:00:00Z',
                'Description': null,
                'ClassType': 'SoftwareHouse.CrossFire.Common.Objects.TimeInterval',
                '*routing': null,
                '*ObjectSize': 348,
                '*id': {
                    '_values': [
                        3
                    ],
                    '_objectTypeName': 'SoftwareHouse.CrossFire.Common.Objects.TimeInterval',
                    '_appServer': 'VM-INGRTN-16-15',
                    'Guid': 'd2d68b64-2f67-4c93-a65b-68c18eb23190',
                    'RoutingInfo': null,
                    'ContextId': '00000000-0000-0000-0000-000000000000',
                    'TransactionID': null
                },
                '*PK': [
                    'ObjectID'
                ],
                '*state': 1,
                '*appServer': 'VM-INGRTN-16-15',
                '*context': '00000000-0000-0000-0000-000000000000',
                '*container': []
            }
        ]
    },
    {
        'January': false,
        'February': false,
        'March': false,
        'April': false,
        'May': false,
        'June': false,
        'July': false,
        'August': false,
        'September': false,
        'October': false,
        'November': false,
        'December': false,
        'ObjectID': 10,
        'Active': false,
        'DayOfMonth': null,
        'Description': 'The default audit log backup schedule that acts on 1:00 AM every Sunday night',
        'DurationTime': '00:00:00',
        'Enabled': true,
        'EndDateTime': '1970-01-01T00:00:00Z',
        'GUID': 'baa68f56-edfc-4165-94b4-d7756ad407b6',
        'IntervalTime': '00:00:00',
        'LastModifiedByID': 1,
        'LastModifiedTime': '2021-07-26T13:53:41.653Z',
        'Name': 'Audit Log Backup Schedule',
        'Protected': true,
        'StartDateTime': '2021-07-26T13:53:41.653',
        'ExpirationDateTime': '1970-01-01T00:00:00Z',
        'TimeZoneID': null,
        'OwnerID': null,
        'OwnerType': null,
        'Template': false,
        'DayOccurrence': 0,
        'Occurrence': 1,
        'Schedule': 1,
        'MonthsOfYear': null,
        'HolidayActive': false,
        'PartitionID': 1,
        'SpecialEditingRequired': false,
        'RecurrenceFrequency': 1,
        'ScheduleEndDateOption': 1,
        'ScheduleEndAfterOccurrence': 0,
        'HourlyScheduleType': 1,
        'RecurrencePatternType': 1,
        'ParentScheduleID': 0,
        'IsRandom': false,
        'YearlySchedule': false,
        'LocationMetaTagFullName': '',
        'ClassType': 'SoftwareHouse.CrossFire.Common.Objects.TimeSpec',
        '*routing': null,
        '*ObjectSize': 399,
        '*id': {
            '_values': [
                10
            ],
            '_objectTypeName': 'SoftwareHouse.CrossFire.Common.Objects.TimeSpec',
            '_appServer': 'VM-INGRTN-16-15',
            'Guid': 'baa68f56-edfc-4165-94b4-d7756ad407b6',
            'RoutingInfo': null,
            'ContextId': '00000000-0000-0000-0000-000000000000',
            'TransactionID': null
        },
        '*PK': [
            'ObjectID'
        ],
        '*state': 1,
        '*appServer': 'VM-INGRTN-16-15',
        '*context': '00000000-0000-0000-0000-000000000000',
        '*container': [
            {
                'StartTimeAsDateTime': null,
                'EndTimeAsDateTime': null,
                'DurationAsString': null,
                'ProcessingOrder': null,
                'NumberOfChangesThisTransaction': null,
                'ObjectID': 10,
                'DurationTime': 600000000,
                'Enabled': false,
                'Friday': false,
                'GUID': '40095640-ac6d-4fb2-8ac3-274d11434307',
                'HolidayGroupId': null,
                'LastModifiedByID': 1,
                'LastModifiedTime': '2021-07-26T13:53:48.11Z',
                'Monday': false,
                'Protected': false,
                'Saturday': false,
                'ScheduleID': 10,
                'StartTime': 36000000000,
                'Sunday': true,
                'Thursday': false,
                'Tuesday': false,
                'Wednesday': false,
                'DefaultRecord': false,
                'Template': false,
                'ParentClassType': 'SoftwareHouse.CrossFire.Common.Objects.TimeSpec',
                'Variance': false,
                'VarianceStartDateTime': '1970-01-01T00:00:00Z',
                'VarianceEndDateTime': '1970-01-01T00:00:00Z',
                'OccurenceDeleted': false,
                'OriginalOccurenceStartDateTime': '1970-01-01T00:00:00Z',
                'OriginalOccurenceEndDateTime': '1970-01-01T00:00:00Z',
                'Description': null,
                'ClassType': 'SoftwareHouse.CrossFire.Common.Objects.TimeInterval',
                '*routing': null,
                '*ObjectSize': 348,
                '*id': {
                    '_values': [
                        10
                    ],
                    '_objectTypeName': 'SoftwareHouse.CrossFire.Common.Objects.TimeInterval',
                    '_appServer': 'VM-INGRTN-16-15',
                    'Guid': '40095640-ac6d-4fb2-8ac3-274d11434307',
                    'RoutingInfo': null,
                    'ContextId': '00000000-0000-0000-0000-000000000000',
                    'TransactionID': null
                },
                '*PK': [
                    'ObjectID'
                ],
                '*state': 1,
                '*appServer': 'VM-INGRTN-16-15',
                '*context': '00000000-0000-0000-0000-000000000000',
                '*container': []
            }
        ]
    },
    {
        'January': false,
        'February': false,
        'March': false,
        'April': false,
        'May': false,
        'June': false,
        'July': false,
        'August': false,
        'September': false,
        'October': false,
        'November': false,
        'December': false,
        'ObjectID': 11,
        'Active': false,
        'DayOfMonth': null,
        'Description': 'The default journal log backup schedule that acts on 1:20 AM every Sunday night',
        'DurationTime': '00:00:00',
        'Enabled': true,
        'EndDateTime': '1970-01-01T00:00:00Z',
        'GUID': '2d9398e9-d1e4-4b51-992c-3884c2e0873c',
        'IntervalTime': '00:00:00',
        'LastModifiedByID': 1,
        'LastModifiedTime': '2021-07-26T13:53:41.653Z',
        'Name': 'Journal Log Backup Schedule',
        'Protected': true,
        'StartDateTime': '2021-07-26T13:53:41.653',
        'ExpirationDateTime': '1970-01-01T00:00:00Z',
        'TimeZoneID': null,
        'OwnerID': null,
        'OwnerType': null,
        'Template': false,
        'DayOccurrence': 0,
        'Occurrence': 1,
        'Schedule': 1,
        'MonthsOfYear': null,
        'HolidayActive': false,
        'PartitionID': 1,
        'SpecialEditingRequired': false,
        'RecurrenceFrequency': 1,
        'ScheduleEndDateOption': 1,
        'ScheduleEndAfterOccurrence': 0,
        'HourlyScheduleType': 1,
        'RecurrencePatternType': 1,
        'ParentScheduleID': 0,
        'IsRandom': false,
        'YearlySchedule': false,
        'LocationMetaTagFullName': '',
        'ClassType': 'SoftwareHouse.CrossFire.Common.Objects.TimeSpec',
        '*routing': null,
        '*ObjectSize': 403,
        '*id': {
            '_values': [
                11
            ],
            '_objectTypeName': 'SoftwareHouse.CrossFire.Common.Objects.TimeSpec',
            '_appServer': 'VM-INGRTN-16-15',
            'Guid': '2d9398e9-d1e4-4b51-992c-3884c2e0873c',
            'RoutingInfo': null,
            'ContextId': '00000000-0000-0000-0000-000000000000',
            'TransactionID': null
        },
        '*PK': [
            'ObjectID'
        ],
        '*state': 1,
        '*appServer': 'VM-INGRTN-16-15',
        '*context': '00000000-0000-0000-0000-000000000000',
        '*container': [
            {
                'StartTimeAsDateTime': null,
                'EndTimeAsDateTime': null,
                'DurationAsString': null,
                'ProcessingOrder': null,
                'NumberOfChangesThisTransaction': null,
                'ObjectID': 11,
                'DurationTime': 600000000,
                'Enabled': false,
                'Friday': false,
                'GUID': 'cc20bf4f-69d2-435b-b08d-ba0691a457fe',
                'HolidayGroupId': null,
                'LastModifiedByID': 1,
                'LastModifiedTime': '2021-07-26T13:53:48.11Z',
                'Monday': false,
                'Protected': false,
                'Saturday': false,
                'ScheduleID': 11,
                'StartTime': 48000000000,
                'Sunday': true,
                'Thursday': false,
                'Tuesday': false,
                'Wednesday': false,
                'DefaultRecord': false,
                'Template': false,
                'ParentClassType': 'SoftwareHouse.CrossFire.Common.Objects.TimeSpec',
                'Variance': false,
                'VarianceStartDateTime': '1970-01-01T00:00:00Z',
                'VarianceEndDateTime': '1970-01-01T00:00:00Z',
                'OccurenceDeleted': false,
                'OriginalOccurenceStartDateTime': '1970-01-01T00:00:00Z',
                'OriginalOccurenceEndDateTime': '1970-01-01T00:00:00Z',
                'Description': null,
                'ClassType': 'SoftwareHouse.CrossFire.Common.Objects.TimeInterval',
                '*routing': null,
                '*ObjectSize': 348,
                '*id': {
                    '_values': [
                        11
                    ],
                    '_objectTypeName': 'SoftwareHouse.CrossFire.Common.Objects.TimeInterval',
                    '_appServer': 'VM-INGRTN-16-15',
                    'Guid': 'cc20bf4f-69d2-435b-b08d-ba0691a457fe',
                    'RoutingInfo': null,
                    'ContextId': '00000000-0000-0000-0000-000000000000',
                    'TransactionID': null
                },
                '*PK': [
                    'ObjectID'
                ],
                '*state': 1,
                '*appServer': 'VM-INGRTN-16-15',
                '*context': '00000000-0000-0000-0000-000000000000',
                '*container': []
            }
        ]
    }
];

export { typeName, table };