const typeName = 'SoftwareHouse.CrossFire.Common.Objects.WebLayout';
const table_all = [
    {
        'Name': 'Access View',
        'PartitionID': 1,
        'ObjectID': 1000,
        'LastModifiedByID': 5344,
        'LastModifiedTime': '2022-02-14T08:00:45.617Z',
        'GUID': 'a091d988-8414-495c-a366-bc4d16ff2791',
        'Description': 'Access view with event viewer and swipe and show',
        'Template': false,
        'Protected': true,
        'SpecialEditingRequired': false,
        'Panes': '[{"id":2001,"cols":5,"rows":3,"x":0,"y":0,"layerIndex":0,"dataObject":{"guid":"ed81d583-7888-45f7-9217-fff051f532d1","key":"EVENTVIEWER","icon":"bolt","description":"Security system event viewer","name":"Event Viewer","loader":{"libPath":"ccure-event-viewer","component":"EventViewerComponent","data":{"Name":"Event Viewer","translationKey":"EVENTVIEWER","Description":"Security system event viewer","GUID":"ed81d583-7888-45f7-9217-fff051f532d1","intrinsic":true}}}},{"id":2002,"cols":2,"rows":3,"x":5,"y":0,"layerIndex":0,"dataObject":{"guid":"f0739385-431e-4a12-8b9f-7be43cefd625","key":"SWIPEANDSHOW","icon":"transfer_within_a_station","description":"Swipe & Show Activity","name":"Swipe & Show","loader":{"libPath":"ccure-swipe-show","component":"SwipeShowComponent","data":{"Name":"Swipe & Show","translationKey":"SWIPEANDSHOW","Description":"Swipe & Show Activity","GUID":"f0739385-431e-4a12-8b9f-7be43cefd625","intrinsic":true}}}}]',
        'Options': '{"gridType":"fit","compactType":"none","allowMultiLayer":true,"defaultLayerIndex":0,"baseLayerIndex":1,"maxLayerIndex":2,"pushItems":false,"swap":true,"swapWhileDragging":false,"margin":0,"outerMargin":false,"outerMarginTop":0,"outerMarginRight":0,"outerMarginBottom":0,"outerMarginLeft":0,"useTransformPositioning":true,"mobileBreakpoint":640,"minCols":1,"maxCols":100,"minRows":1,"maxRows":100,"maxItemCols":100,"minItemCols":1,"maxItemRows":100,"minItemRows":1,"maxItemArea":2500,"minItemArea":1,"defaultItemCols":1,"defaultItemRows":1,"fixedColWidth":150,"fixedRowHeight":150,"keepFixedHeightInMobile":false,"keepFixedWidthInMobile":false,"scrollSensitivity":10,"scrollSpeed":20,"enableEmptyCellClick":true,"enableEmptyCellContextMenu":false,"enableEmptyCellDrop":true,"enableEmptyCellDrag":false,"enableOccupiedCellDrop":true,"emptyCellDragMaxCols":50,"emptyCellDragMaxRows":50,"ignoreMarginInRow":false,"draggable":{"enabled":true},"resizable":{"enabled":true},"pushDirections":{"north":true,"east":true,"south":true,"west":true},"disablePushOnDrag":false,"disablePushOnResize":false,"pushResizeItems":true,"displayGrid":"always","disableWindowResize":false,"disableWarnings":false,"scrollToNewItems":false}',
        'Locked': false,
        'SaveAsDefault': false,
        'AutoCloseOnAck': false,
        'ConfirmOnAutoClose': false,
        'LayoutOpen': false,
        'AutoCloseOnClear': false,
        'ConfirmEventClearOnAutoClose': false,
        'AllowFiltering': false,
        'ShowMaintenanceObject': null,
        'LayoutType': 0,
        'RefreshType': 0,
        'WebLayoutType': null,
        'WidgetsPartitionID': null,
        'ClassType': 'SoftwareHouse.CrossFire.Common.Objects.WebLayout',
        '*routing': null,
        '*ObjectSize': 2508,
        '*id': {
            '_values': [
                1000
            ],
            '_objectTypeName': 'SoftwareHouse.CrossFire.Common.Objects.WebLayout',
            '_appServer': 'VM-INGRTN-16-15',
            'Guid': 'a091d988-8414-495c-a366-bc4d16ff2791',
            'RoutingInfo': null,
            'ContextId': '00000000-0000-0000-0000-000000000000',
            'TransactionID': null
        },
        '*PK': [
            'ObjectID'
        ],
        '*state': 1,
        '*appServer': 'VM-INGRTN-16-15',
        '*context': '00000000-0000-0000-0000-000000000000',
        '*container': []
    },
    {
        'Name': 'Access View and Video',
        'PartitionID': 1,
        'ObjectID': 1001,
        'LastModifiedByID': 5344,
        'LastModifiedTime': '2022-02-14T08:00:45.617Z',
        'GUID': '9d886583-eaaf-45eb-96d3-2da4305785c0',
        'Description': 'Access view with event viewer, swipe and show and video',
        'Template': false,
        'Protected': true,
        'SpecialEditingRequired': false,
        'Panes': '[{"id":2003,"cols":3,"rows":2,"x":0,"y":0,"layerIndex":0,"dataObject":{"guid":"ed81d583-7888-45f7-9217-fff051f532d1","key":"EVENTVIEWER","icon":"bolt","description":"Security system event viewer","name":"Event Viewer","loader":{"libPath":"ccure-event-viewer","component":"EventViewerComponent","data":{"Name":"Event Viewer","translationKey":"EVENTVIEWER","Description":"Security system event viewer","GUID":"ed81d583-7888-45f7-9217-fff051f532d1","intrinsic":true}}}},{"id":2004,"cols":3,"rows":1,"x":0,"y":2,"layerIndex":0,"dataObject":{"guid":"f0739385-431e-4a12-8b9f-7be43cefd625","key":"SWIPEANDSHOW","icon":"transfer_within_a_station","description":"Swipe & Show Activity","name":"Swipe & Show","loader":{"libPath":"ccure-swipe-show","component":"SwipeShowComponent","data":{"Name":"Swipe & Show","translationKey":"SWIPEANDSHOW","Description":"Swipe & Show Activity","GUID":"f0739385-431e-4a12-8b9f-7be43cefd625","intrinsic":true}}}},{"id":2005,"cols":4,"rows":3,"x":3,"y":0,"layerIndex":0,"dataObject":{"guid":"df8fa35c-7253-495a-b72a-6d1d503fbcde","key":"VIDEOMONITORING","icon":"video_call","description":"Video Monitoring Activity","name":"Video Monitoring","loader":{"libPath":"ccure-video-monitor","component":"entry","data":{"Name":"Video Monitoring","translationKey":"VIDEOMONITORING","Description":"Video Monitoring Activity","GUID":"df8fa35c-7253-495a-b72a-6d1d503fbcde","intrinsic":true}}}}]',
        'Options': '{"gridType":"fit","compactType":"none","allowMultiLayer":true,"defaultLayerIndex":0,"baseLayerIndex":1,"maxLayerIndex":2,"pushItems":false,"swap":true,"swapWhileDragging":false,"margin":0,"outerMargin":false,"outerMarginTop":0,"outerMarginRight":0,"outerMarginBottom":0,"outerMarginLeft":0,"useTransformPositioning":true,"mobileBreakpoint":640,"minCols":1,"maxCols":100,"minRows":1,"maxRows":100,"maxItemCols":100,"minItemCols":1,"maxItemRows":100,"minItemRows":1,"maxItemArea":2500,"minItemArea":1,"defaultItemCols":1,"defaultItemRows":1,"fixedColWidth":150,"fixedRowHeight":150,"keepFixedHeightInMobile":false,"keepFixedWidthInMobile":false,"scrollSensitivity":10,"scrollSpeed":20,"enableEmptyCellClick":true,"enableEmptyCellContextMenu":false,"enableEmptyCellDrop":true,"enableEmptyCellDrag":false,"enableOccupiedCellDrop":true,"emptyCellDragMaxCols":50,"emptyCellDragMaxRows":50,"ignoreMarginInRow":false,"draggable":{"enabled":true},"resizable":{"enabled":true},"pushDirections":{"north":true,"east":true,"south":true,"west":true},"disablePushOnDrag":false,"disablePushOnResize":false,"pushResizeItems":true,"displayGrid":"always","disableWindowResize":false,"disableWarnings":false,"scrollToNewItems":false}',
        'Locked': false,
        'SaveAsDefault': false,
        'AutoCloseOnAck': false,
        'ConfirmOnAutoClose': false,
        'LayoutOpen': false,
        'AutoCloseOnClear': false,
        'ConfirmEventClearOnAutoClose': false,
        'AllowFiltering': false,
        'ShowMaintenanceObject': null,
        'LayoutType': 0,
        'RefreshType': 0,
        'WebLayoutType': null,
        'WidgetsPartitionID': null,
        'ClassType': 'SoftwareHouse.CrossFire.Common.Objects.WebLayout',
        '*routing': null,
        '*ObjectSize': 2993,
        '*id': {
            '_values': [
                1001
            ],
            '_objectTypeName': 'SoftwareHouse.CrossFire.Common.Objects.WebLayout',
            '_appServer': 'VM-INGRTN-16-15',
            'Guid': '9d886583-eaaf-45eb-96d3-2da4305785c0',
            'RoutingInfo': null,
            'ContextId': '00000000-0000-0000-0000-000000000000',
            'TransactionID': null
        },
        '*PK': [
            'ObjectID'
        ],
        '*state': 1,
        '*appServer': 'VM-INGRTN-16-15',
        '*context': '00000000-0000-0000-0000-000000000000',
        '*container': []
    },
    {
        'Name': 'Event Viewer',
        'PartitionID': 1,
        'ObjectID': 1002,
        'LastModifiedByID': 5344,
        'LastModifiedTime': '2022-02-14T08:00:45.617Z',
        'GUID': '8421e1e6-4eeb-49e3-be6e-2ee6d3cbc689',
        'Description': 'Event Viewer',
        'Template': false,
        'Protected': true,
        'SpecialEditingRequired': false,
        'Panes': '[{"id":1002,"cols":1,"rows":1,"x":0,"y":0,"layerIndex":0,"dataObject":{"guid":"ed81d583-7888-45f7-9217-fff051f532d1","key":"EVENTVIEWER","icon":"bolt","description":"Security system event viewer","name":"Event Viewer","loader":{"libPath":"ccure-event-viewer","component":"EventViewerComponent","data":{"Name":"Event Viewer","translationKey":"EVENTVIEWER","Description":"Security system event viewer","GUID":"ed81d583-7888-45f7-9217-fff051f532d1","intrinsic":true}}}}]',
        'Options': '{"gridType":"fit","compactType":"none","allowMultiLayer":true,"defaultLayerIndex":0,"baseLayerIndex":1,"maxLayerIndex":2,"pushItems":false,"swap":true,"swapWhileDragging":false,"margin":0,"outerMargin":false,"outerMarginTop":0,"outerMarginRight":0,"outerMarginBottom":0,"outerMarginLeft":0,"useTransformPositioning":true,"mobileBreakpoint":640,"minCols":1,"maxCols":100,"minRows":1,"maxRows":100,"maxItemCols":100,"minItemCols":1,"maxItemRows":100,"minItemRows":1,"maxItemArea":2500,"minItemArea":1,"defaultItemCols":1,"defaultItemRows":1,"fixedColWidth":150,"fixedRowHeight":150,"keepFixedHeightInMobile":false,"keepFixedWidthInMobile":false,"scrollSensitivity":10,"scrollSpeed":20,"enableEmptyCellClick":true,"enableEmptyCellContextMenu":false,"enableEmptyCellDrop":true,"enableEmptyCellDrag":false,"enableOccupiedCellDrop":true,"emptyCellDragMaxCols":50,"emptyCellDragMaxRows":50,"ignoreMarginInRow":false,"draggable":{"enabled":true},"resizable":{"enabled":true},"pushDirections":{"north":true,"east":true,"south":true,"west":true},"disablePushOnDrag":false,"disablePushOnResize":false,"pushResizeItems":true,"displayGrid":"always","disableWindowResize":false,"disableWarnings":false,"scrollToNewItems":false}',
        'Locked': false,
        'SaveAsDefault': false,
        'AutoCloseOnAck': false,
        'ConfirmOnAutoClose': false,
        'LayoutOpen': false,
        'AutoCloseOnClear': false,
        'ConfirmEventClearOnAutoClose': false,
        'AllowFiltering': false,
        'ShowMaintenanceObject': null,
        'LayoutType': 0,
        'RefreshType': 0,
        'WebLayoutType': null,
        'WidgetsPartitionID': null,
        'ClassType': 'SoftwareHouse.CrossFire.Common.Objects.WebLayout',
        '*routing': null,
        '*ObjectSize': 2002,
        '*id': {
            '_values': [
                1002
            ],
            '_objectTypeName': 'SoftwareHouse.CrossFire.Common.Objects.WebLayout',
            '_appServer': 'VM-INGRTN-16-15',
            'Guid': '8421e1e6-4eeb-49e3-be6e-2ee6d3cbc689',
            'RoutingInfo': null,
            'ContextId': '00000000-0000-0000-0000-000000000000',
            'TransactionID': null
        },
        '*PK': [
            'ObjectID'
        ],
        '*state': 1,
        '*appServer': 'VM-INGRTN-16-15',
        '*context': '00000000-0000-0000-0000-000000000000',
        '*container': []
    },
    {
        'Name': 'Video Monitoring',
        'PartitionID': 1,
        'ObjectID': 1003,
        'LastModifiedByID': 5344,
        'LastModifiedTime': '2022-02-14T08:00:45.617Z',
        'GUID': 'e2a17982-4af8-4d07-9517-b7be6a08db6c',
        'Description': 'Video Monitoring Activity',
        'Template': false,
        'Protected': true,
        'SpecialEditingRequired': false,
        'Panes': '[{"id":1003,"cols":1,"rows":1,"x":0,"y":0,"layerIndex":0,"dataObject":{"guid":"df8fa35c-7253-495a-b72a-6d1d503fbcde","key":"VIDEOMONITORING","icon":"video_call","description":"Video Monitoring Activity","name":"Video Monitoring","loader":{"libPath":"ccure-video-monitor","component":"entry","data":{"Name":"Video Monitoring","translationKey":"VIDEOMONITORING","Description":"Video Monitoring Activity","GUID":"df8fa35c-7253-495a-b72a-6d1d503fbcde","intrinsic":true}}}}]',
        'Options': '{"gridType":"fit","compactType":"none","allowMultiLayer":true,"defaultLayerIndex":0,"baseLayerIndex":1,"maxLayerIndex":2,"pushItems":false,"swap":true,"swapWhileDragging":false,"margin":0,"outerMargin":false,"outerMarginTop":0,"outerMarginRight":0,"outerMarginBottom":0,"outerMarginLeft":0,"useTransformPositioning":true,"mobileBreakpoint":640,"minCols":1,"maxCols":100,"minRows":1,"maxRows":100,"maxItemCols":100,"minItemCols":1,"maxItemRows":100,"minItemRows":1,"maxItemArea":2500,"minItemArea":1,"defaultItemCols":1,"defaultItemRows":1,"fixedColWidth":150,"fixedRowHeight":150,"keepFixedHeightInMobile":false,"keepFixedWidthInMobile":false,"scrollSensitivity":10,"scrollSpeed":20,"enableEmptyCellClick":true,"enableEmptyCellContextMenu":false,"enableEmptyCellDrop":true,"enableEmptyCellDrag":false,"enableOccupiedCellDrop":true,"emptyCellDragMaxCols":50,"emptyCellDragMaxRows":50,"ignoreMarginInRow":false,"draggable":{"enabled":true},"resizable":{"enabled":true},"pushDirections":{"north":true,"east":true,"south":true,"west":true},"disablePushOnDrag":false,"disablePushOnResize":false,"pushResizeItems":true,"displayGrid":"always","disableWindowResize":false,"disableWarnings":false,"scrollToNewItems":false}',
        'Locked': false,
        'SaveAsDefault': false,
        'AutoCloseOnAck': false,
        'ConfirmOnAutoClose': false,
        'LayoutOpen': false,
        'AutoCloseOnClear': false,
        'ConfirmEventClearOnAutoClose': false,
        'AllowFiltering': false,
        'ShowMaintenanceObject': null,
        'LayoutType': 0,
        'RefreshType': 0,
        'WebLayoutType': null,
        'WidgetsPartitionID': null,
        'ClassType': 'SoftwareHouse.CrossFire.Common.Objects.WebLayout',
        '*routing': null,
        '*ObjectSize': 2021,
        '*id': {
            '_values': [
                1003
            ],
            '_objectTypeName': 'SoftwareHouse.CrossFire.Common.Objects.WebLayout',
            '_appServer': 'VM-INGRTN-16-15',
            'Guid': 'e2a17982-4af8-4d07-9517-b7be6a08db6c',
            'RoutingInfo': null,
            'ContextId': '00000000-0000-0000-0000-000000000000',
            'TransactionID': null
        },
        '*PK': [
            'ObjectID'
        ],
        '*state': 1,
        '*appServer': 'VM-INGRTN-16-15',
        '*context': '00000000-0000-0000-0000-000000000000',
        '*container': []
    },
    {
        'Name': 'Swipe and Show',
        'PartitionID': 1,
        'ObjectID': 1004,
        'LastModifiedByID': 5344,
        'LastModifiedTime': '2022-02-14T08:00:45.617Z',
        'GUID': '89fd47d4-8158-4ed2-a8fa-2163e2f8961e',
        'Description': 'Swipe and Show Activity',
        'Template': false,
        'Protected': true,
        'SpecialEditingRequired': false,
        'Panes': '[{"id":1004,"cols":1,"rows":1,"x":0,"y":0,"layerIndex":0,"dataObject":{"guid":"f0739385-431e-4a12-8b9f-7be43cefd625","key":"SWIPEANDSHOW","icon":"transfer_within_a_station","description":"Swipe & Show Activity","name":"Swipe & Show","loader":{"libPath":"ccure-swipe-show","component":"SwipeShowComponent","data":{"Name":"Swipe & Show","translationKey":"SWIPEANDSHOW","Description":"Swipe & Show Activity","GUID":"f0739385-431e-4a12-8b9f-7be43cefd625","intrinsic":true}}}}]',
        'Options': '{"gridType":"fit","compactType":"none","allowMultiLayer":true,"defaultLayerIndex":0,"baseLayerIndex":1,"maxLayerIndex":2,"pushItems":false,"swap":true,"swapWhileDragging":false,"margin":0,"outerMargin":false,"outerMarginTop":0,"outerMarginRight":0,"outerMarginBottom":0,"outerMarginLeft":0,"useTransformPositioning":true,"mobileBreakpoint":640,"minCols":1,"maxCols":100,"minRows":1,"maxRows":100,"maxItemCols":100,"minItemCols":1,"maxItemRows":100,"minItemRows":1,"maxItemArea":2500,"minItemArea":1,"defaultItemCols":1,"defaultItemRows":1,"fixedColWidth":150,"fixedRowHeight":150,"keepFixedHeightInMobile":false,"keepFixedWidthInMobile":false,"scrollSensitivity":10,"scrollSpeed":20,"enableEmptyCellClick":true,"enableEmptyCellContextMenu":false,"enableEmptyCellDrop":true,"enableEmptyCellDrag":false,"enableOccupiedCellDrop":true,"emptyCellDragMaxCols":50,"emptyCellDragMaxRows":50,"ignoreMarginInRow":false,"draggable":{"enabled":true},"resizable":{"enabled":true},"pushDirections":{"north":true,"east":true,"south":true,"west":true},"disablePushOnDrag":false,"disablePushOnResize":false,"pushResizeItems":true,"displayGrid":"always","disableWindowResize":false,"disableWarnings":false,"scrollToNewItems":false}',
        'Locked': false,
        'SaveAsDefault': false,
        'AutoCloseOnAck': false,
        'ConfirmOnAutoClose': false,
        'LayoutOpen': false,
        'AutoCloseOnClear': false,
        'ConfirmEventClearOnAutoClose': false,
        'AllowFiltering': false,
        'ShowMaintenanceObject': null,
        'LayoutType': 0,
        'RefreshType': 0,
        'WebLayoutType': null,
        'WidgetsPartitionID': null,
        'ClassType': 'SoftwareHouse.CrossFire.Common.Objects.WebLayout',
        '*routing': null,
        '*ObjectSize': 2020,
        '*id': {
            '_values': [
                1004
            ],
            '_objectTypeName': 'SoftwareHouse.CrossFire.Common.Objects.WebLayout',
            '_appServer': 'VM-INGRTN-16-15',
            'Guid': '89fd47d4-8158-4ed2-a8fa-2163e2f8961e',
            'RoutingInfo': null,
            'ContextId': '00000000-0000-0000-0000-000000000000',
            'TransactionID': null
        },
        '*PK': [
            'ObjectID'
        ],
        '*state': 1,
        '*appServer': 'VM-INGRTN-16-15',
        '*context': '00000000-0000-0000-0000-000000000000',
        '*container': []
    },
    {
        'Name': 'Personnel Monitoring',
        'PartitionID': 1,
        'ObjectID': 1005,
        'LastModifiedByID': 5344,
        'LastModifiedTime': '2022-02-14T08:00:45.617Z',
        'GUID': 'c49da43a-7bce-4660-a9ae-c4e2631b4e5d',
        'Description': 'Personnel Monitoring Activity',
        'Template': false,
        'Protected': true,
        'SpecialEditingRequired': false,
        'Panes': '[{"id":1005,"cols":1,"rows":1,"x":0,"y":0,"layerIndex":0,"dataObject":{"guid":"fae34b07-be27-445a-b7ce-0cde58814b0a","key":"PERSONNELMONITORING","icon":"person","description":"Personnel Monitoring Activity","name":"Personnel Monitoring","loader":{"libPath":"ccure-personnel-monitoring","component":"PersonnelMonitoringComponent","data":{"Name":"Personnel Monitoring","translationKey":"PERSONNELMONITORING","Description":"Personnel Monitoring Activity","GUID":"fae34b07-be27-445a-b7ce-0cde58814b0a","intrinsic":true}}}}]',
        'Options': '{"gridType":"fit","compactType":"none","allowMultiLayer":true,"defaultLayerIndex":0,"baseLayerIndex":1,"maxLayerIndex":2,"pushItems":false,"swap":true,"swapWhileDragging":false,"margin":0,"outerMargin":false,"outerMarginTop":0,"outerMarginRight":0,"outerMarginBottom":0,"outerMarginLeft":0,"useTransformPositioning":true,"mobileBreakpoint":640,"minCols":1,"maxCols":100,"minRows":1,"maxRows":100,"maxItemCols":100,"minItemCols":1,"maxItemRows":100,"minItemRows":1,"maxItemArea":2500,"minItemArea":1,"defaultItemCols":1,"defaultItemRows":1,"fixedColWidth":150,"fixedRowHeight":150,"keepFixedHeightInMobile":false,"keepFixedWidthInMobile":false,"scrollSensitivity":10,"scrollSpeed":20,"enableEmptyCellClick":true,"enableEmptyCellContextMenu":false,"enableEmptyCellDrop":true,"enableEmptyCellDrag":false,"enableOccupiedCellDrop":true,"emptyCellDragMaxCols":50,"emptyCellDragMaxRows":50,"ignoreMarginInRow":false,"draggable":{"enabled":true},"resizable":{"enabled":true},"pushDirections":{"north":true,"east":true,"south":true,"west":true},"disablePushOnDrag":false,"disablePushOnResize":false,"pushResizeItems":true,"displayGrid":"always","disableWindowResize":false,"disableWarnings":false,"scrollToNewItems":false}',
        'Locked': false,
        'SaveAsDefault': false,
        'AutoCloseOnAck': false,
        'ConfirmOnAutoClose': false,
        'LayoutOpen': false,
        'AutoCloseOnClear': false,
        'ConfirmEventClearOnAutoClose': false,
        'AllowFiltering': false,
        'ShowMaintenanceObject': null,
        'LayoutType': 0,
        'RefreshType': 0,
        'WebLayoutType': null,
        'WidgetsPartitionID': null,
        'ClassType': 'SoftwareHouse.CrossFire.Common.Objects.WebLayout',
        '*routing': null,
        '*ObjectSize': 2079,
        '*id': {
            '_values': [
                1005
            ],
            '_objectTypeName': 'SoftwareHouse.CrossFire.Common.Objects.WebLayout',
            '_appServer': 'VM-INGRTN-16-15',
            'Guid': 'c49da43a-7bce-4660-a9ae-c4e2631b4e5d',
            'RoutingInfo': null,
            'ContextId': '00000000-0000-0000-0000-000000000000',
            'TransactionID': null
        },
        '*PK': [
            'ObjectID'
        ],
        '*state': 1,
        '*appServer': 'VM-INGRTN-16-15',
        '*context': '00000000-0000-0000-0000-000000000000',
        '*container': []
    },
    {
        'Name': 'Video Search',
        'PartitionID': 1,
        'ObjectID': 1006,
        'LastModifiedByID': 5344,
        'LastModifiedTime': '2022-02-14T08:00:45.617Z',
        'GUID': 'aa359213-289a-4262-a3c8-6b70c335ab77',
        'Description': 'Video Search Activity',
        'Template': false,
        'Protected': true,
        'SpecialEditingRequired': false,
        'Panes': '[{"id":1006,"cols":1,"rows":1,"x":0,"y":0,"layerIndex":0,"dataObject":{"guid":"3d2bd399-c1da-4c31-8cbe-a4c301640c3f","key":"VIDEOSEARCH","icon":"search","description":"Video Search Activity","name":"Video Search","loader":{"libPath":"ccure-video-search","component":"entry","data":{"Name":"Video Search","translationKey":"VIDEOSEARCH","Description":"Video Search Activity","GUID":"3d2bd399-c1da-4c31-8cbe-a4c301640c3f","intrinsic":true}}}}]',
        'Options': '{"gridType":"fit","compactType":"none","allowMultiLayer":true,"defaultLayerIndex":0,"baseLayerIndex":1,"maxLayerIndex":2,"pushItems":false,"swap":true,"swapWhileDragging":false,"margin":0,"outerMargin":false,"outerMarginTop":0,"outerMarginRight":0,"outerMarginBottom":0,"outerMarginLeft":0,"useTransformPositioning":true,"mobileBreakpoint":640,"minCols":1,"maxCols":100,"minRows":1,"maxRows":100,"maxItemCols":100,"minItemCols":1,"maxItemRows":100,"minItemRows":1,"maxItemArea":2500,"minItemArea":1,"defaultItemCols":1,"defaultItemRows":1,"fixedColWidth":150,"fixedRowHeight":150,"keepFixedHeightInMobile":false,"keepFixedWidthInMobile":false,"scrollSensitivity":10,"scrollSpeed":20,"enableEmptyCellClick":true,"enableEmptyCellContextMenu":false,"enableEmptyCellDrop":true,"enableEmptyCellDrag":false,"enableOccupiedCellDrop":true,"emptyCellDragMaxCols":50,"emptyCellDragMaxRows":50,"ignoreMarginInRow":false,"draggable":{"enabled":true},"resizable":{"enabled":true},"pushDirections":{"north":true,"east":true,"south":true,"west":true},"disablePushOnDrag":false,"disablePushOnResize":false,"pushResizeItems":true,"displayGrid":"always","disableWindowResize":false,"disableWarnings":false,"scrollToNewItems":false}',
        'Locked': false,
        'SaveAsDefault': false,
        'AutoCloseOnAck': false,
        'ConfirmOnAutoClose': false,
        'LayoutOpen': false,
        'AutoCloseOnClear': false,
        'ConfirmEventClearOnAutoClose': false,
        'AllowFiltering': false,
        'ShowMaintenanceObject': null,
        'LayoutType': 0,
        'RefreshType': 0,
        'WebLayoutType': null,
        'WidgetsPartitionID': null,
        'ClassType': 'SoftwareHouse.CrossFire.Common.Objects.WebLayout',
        '*routing': null,
        '*ObjectSize': 1984,
        '*id': {
            '_values': [
                1006
            ],
            '_objectTypeName': 'SoftwareHouse.CrossFire.Common.Objects.WebLayout',
            '_appServer': 'VM-INGRTN-16-15',
            'Guid': 'aa359213-289a-4262-a3c8-6b70c335ab77',
            'RoutingInfo': null,
            'ContextId': '00000000-0000-0000-0000-000000000000',
            'TransactionID': null
        },
        '*PK': [
            'ObjectID'
        ],
        '*state': 1,
        '*appServer': 'VM-INGRTN-16-15',
        '*context': '00000000-0000-0000-0000-000000000000',
        '*container': []
    },
    {
        'Name': 'System Health Dashboard',
        'PartitionID': 1,
        'ObjectID': 1007,
        'LastModifiedByID': 5344,
        'LastModifiedTime': '2022-02-14T08:00:45.617Z',
        'GUID': '97ceca9b-c78e-4265-b788-214e0f7b98cd',
        'Description': 'System health performance dashboard',
        'Template': false,
        'Protected': true,
        'SpecialEditingRequired': false,
        'Panes': '[{"id":1001,"cols":1,"rows":1,"x":0,"y":0,"layerIndex":0,"dataObject":{"guid":"2fe7a413-0999-4847-9f99-7ac26bf2351c","key":"DASHBOARD","icon":"dashboard","description":"Overall system health performance dashboard","name":"System health dashboard","loader":{"libPath":"ccure-dashboard-viewer","component":"SystemHealthComponent","data":{"Name":"System health dashboard","translationKey":"DASHBOARD","Description":"Overall system health performance dashboard","GUID":"2fe7a413-0999-4847-9f99-7ac26bf2351c","intrinsic":true}}}}]',
        'Options': '{"gridType":"fit","compactType":"none","allowMultiLayer":true,"defaultLayerIndex":0,"baseLayerIndex":1,"maxLayerIndex":2,"pushItems":false,"swap":true,"swapWhileDragging":false,"margin":0,"outerMargin":false,"outerMarginTop":0,"outerMarginRight":0,"outerMarginBottom":0,"outerMarginLeft":0,"useTransformPositioning":true,"mobileBreakpoint":640,"minCols":1,"maxCols":100,"minRows":1,"maxRows":100,"maxItemCols":100,"minItemCols":1,"maxItemRows":100,"minItemRows":1,"maxItemArea":2500,"minItemArea":1,"defaultItemCols":1,"defaultItemRows":1,"fixedColWidth":150,"fixedRowHeight":150,"keepFixedHeightInMobile":false,"keepFixedWidthInMobile":false,"scrollSensitivity":10,"scrollSpeed":20,"enableEmptyCellClick":true,"enableEmptyCellContextMenu":false,"enableEmptyCellDrop":true,"enableEmptyCellDrag":false,"enableOccupiedCellDrop":true,"emptyCellDragMaxCols":50,"emptyCellDragMaxRows":50,"ignoreMarginInRow":false,"draggable":{"enabled":true},"resizable":{"enabled":true},"pushDirections":{"north":true,"east":true,"south":true,"west":true},"disablePushOnDrag":false,"disablePushOnResize":false,"pushResizeItems":true,"displayGrid":"always","disableWindowResize":false,"disableWarnings":false,"scrollToNewItems":false}',
        'Locked': false,
        'SaveAsDefault': false,
        'AutoCloseOnAck': false,
        'ConfirmOnAutoClose': false,
        'LayoutOpen': false,
        'AutoCloseOnClear': false,
        'ConfirmEventClearOnAutoClose': false,
        'AllowFiltering': false,
        'ShowMaintenanceObject': null,
        'LayoutType': 0,
        'RefreshType': 0,
        'WebLayoutType': null,
        'WidgetsPartitionID': null,
        'ClassType': 'SoftwareHouse.CrossFire.Common.Objects.WebLayout',
        '*routing': null,
        '*ObjectSize': 2094,
        '*id': {
            '_values': [
                1007
            ],
            '_objectTypeName': 'SoftwareHouse.CrossFire.Common.Objects.WebLayout',
            '_appServer': 'VM-INGRTN-16-15',
            'Guid': '97ceca9b-c78e-4265-b788-214e0f7b98cd',
            'RoutingInfo': null,
            'ContextId': '00000000-0000-0000-0000-000000000000',
            'TransactionID': null
        },
        '*PK': [
            'ObjectID'
        ],
        '*state': 1,
        '*appServer': 'VM-INGRTN-16-15',
        '*context': '00000000-0000-0000-0000-000000000000',
        '*container': []
    },
    {
        'Name': 'Default',
        'PartitionID': 1,
        'ObjectID': 5000,
        'LastModifiedByID': 5000,
        'LastModifiedTime': '2021-10-08T14:06:33.363Z',
        'GUID': '65e65cc9-b11a-49ec-a981-82b0a43debdd',
        'Description': 'Default system dashboard',
        'Template': false,
        'Protected': true,
        'SpecialEditingRequired': false,
        'Panes': '[{"id":6364,"cols":1,"rows":1,"x":0,"y":0,"layerIndex":0,"dataObject":{"guid":"58048bd4-bf36-47bc-96ce-82ae0d7d960d","key":"DASHBOARD","icon":"dashboard","description":"Overall security system performance dashboard","name":"Server dashboard","loader":{"libPath":"ccure-dashboard-viewer","component":"DashboardComponent","data":{"Name":"Server dashboard","translationKey":null,"Description":"Overall security system performance dashboard","GUID":"58048bd4-bf36-47bc-96ce-82ae0d7d960d"}}}}]',
        'Options': '{"gridType":"fit","compactType":"none","allowMultiLayer":true,"defaultLayerIndex":0,"baseLayerIndex":1,"maxLayerIndex":2,"pushItems":false,"swap":true,"swapWhileDragging":false,"margin":0,"outerMargin":false,"outerMarginTop":0,"outerMarginRight":0,"outerMarginBottom":0,"outerMarginLeft":0,"useTransformPositioning":true,"mobileBreakpoint":640,"minCols":1,"maxCols":100,"minRows":1,"maxRows":100,"maxItemCols":100,"minItemCols":1,"maxItemRows":100,"minItemRows":1,"maxItemArea":2500,"minItemArea":1,"defaultItemCols":1,"defaultItemRows":1,"fixedColWidth":150,"fixedRowHeight":150,"keepFixedHeightInMobile":false,"keepFixedWidthInMobile":false,"scrollSensitivity":10,"scrollSpeed":20,"enableEmptyCellClick":true,"enableEmptyCellContextMenu":false,"enableEmptyCellDrop":true,"enableEmptyCellDrag":false,"enableOccupiedCellDrop":true,"emptyCellDragMaxCols":50,"emptyCellDragMaxRows":50,"ignoreMarginInRow":false,"draggable":{"enabled":true},"resizable":{"enabled":true},"pushDirections":{"north":true,"east":true,"south":true,"west":true},"disablePushOnDrag":false,"disablePushOnResize":false,"pushResizeItems":true,"displayGrid":"always","disableWindowResize":false,"disableWarnings":false,"scrollToNewItems":false}',
        'Locked': false,
        'SaveAsDefault': false,
        'AutoCloseOnAck': false,
        'ConfirmOnAutoClose': false,
        'LayoutOpen': false,
        'AutoCloseOnClear': false,
        'ConfirmEventClearOnAutoClose': false,
        'AllowFiltering': false,
        'ShowMaintenanceObject': null,
        'LayoutType': 0,
        'RefreshType': 0,
        'WebLayoutType': null,
        'WidgetsPartitionID': null,
        'ClassType': 'SoftwareHouse.CrossFire.Common.Objects.WebLayout',
        '*routing': null,
        '*ObjectSize': 2030,
        '*id': {
            '_values': [
                5000
            ],
            '_objectTypeName': 'SoftwareHouse.CrossFire.Common.Objects.WebLayout',
            '_appServer': 'VM-INGRTN-16-15',
            'Guid': '65e65cc9-b11a-49ec-a981-82b0a43debdd',
            'RoutingInfo': null,
            'ContextId': '00000000-0000-0000-0000-000000000000',
            'TransactionID': null
        },
        '*PK': [
            'ObjectID'
        ],
        '*state': 1,
        '*appServer': 'VM-INGRTN-16-15',
        '*context': '00000000-0000-0000-0000-000000000000',
        '*container': []
    },
    {
        'Name': 'Access View & Video',
        'PartitionID': 1,
        'ObjectID': 5001,
        'LastModifiedByID': 5000,
        'LastModifiedTime': '2022-02-14T09:35:02.373Z',
        'GUID': '98087add-591b-473d-bea2-ae0e663ae03b',
        'Description': 'Access view with event viewer, swipe and show and video',
        'Template': false,
        'Protected': true,
        'SpecialEditingRequired': false,
        'Panes': '[{"id":2003,"cols":3,"rows":2,"x":0,"y":0,"layerIndex":0,"dataObject":{"guid":"ed81d583-7888-45f7-9217-fff051f532d1","key":"EVENTVIEWER","icon":"bolt","description":"Security system event viewer","name":"Event Viewer","loader":{"libPath":"ccure-event-viewer","component":"EventViewerComponent","data":{"Name":"Event Viewer","translationKey":"EVENTVIEWER","Description":"Security system event viewer","GUID":"ed81d583-7888-45f7-9217-fff051f532d1","intrinsic":true}}}},{"id":2004,"cols":3,"rows":1,"x":0,"y":2,"layerIndex":0,"dataObject":{"guid":"f0739385-431e-4a12-8b9f-7be43cefd625","key":"SWIPEANDSHOW","icon":"transfer_within_a_station","description":"Swipe & Show Activity","name":"Swipe & Show","loader":{"libPath":"ccure-swipe-show","component":"SwipeShowComponent","data":{"Name":"Swipe & Show","translationKey":"SWIPEANDSHOW","Description":"Swipe & Show Activity","GUID":"f0739385-431e-4a12-8b9f-7be43cefd625","intrinsic":true}}}},{"id":2005,"cols":4,"rows":3,"x":3,"y":0,"layerIndex":0,"dataObject":{"guid":"df8fa35c-7253-495a-b72a-6d1d503fbcde","key":"VIDEOMONITORING","icon":"video_call","description":"Video Monitoring Activity","name":"Video Monitoring","loader":{"libPath":"ccure-video-monitor","component":"entry","data":{"Name":"Video Monitoring","translationKey":"VIDEOMONITORING","Description":"Video Monitoring Activity","GUID":"df8fa35c-7253-495a-b72a-6d1d503fbcde","intrinsic":true}}}}]',
        'Options': '{"gridType":"fit","compactType":"none","allowMultiLayer":true,"defaultLayerIndex":0,"baseLayerIndex":1,"maxLayerIndex":2,"pushItems":false,"swap":true,"swapWhileDragging":false,"margin":0,"outerMargin":false,"outerMarginTop":0,"outerMarginRight":0,"outerMarginBottom":0,"outerMarginLeft":0,"useTransformPositioning":true,"mobileBreakpoint":640,"minCols":1,"maxCols":100,"minRows":1,"maxRows":100,"maxItemCols":100,"minItemCols":1,"maxItemRows":100,"minItemRows":1,"maxItemArea":2500,"minItemArea":1,"defaultItemCols":1,"defaultItemRows":1,"fixedColWidth":150,"fixedRowHeight":150,"keepFixedHeightInMobile":false,"keepFixedWidthInMobile":false,"scrollSensitivity":10,"scrollSpeed":20,"enableEmptyCellClick":true,"enableEmptyCellContextMenu":false,"enableEmptyCellDrop":true,"enableEmptyCellDrag":false,"enableOccupiedCellDrop":true,"emptyCellDragMaxCols":50,"emptyCellDragMaxRows":50,"ignoreMarginInRow":false,"draggable":{"enabled":true},"resizable":{"enabled":true},"pushDirections":{"north":true,"east":true,"south":true,"west":true},"disablePushOnDrag":false,"disablePushOnResize":false,"pushResizeItems":true,"displayGrid":"always","disableWindowResize":false,"disableWarnings":false,"scrollToNewItems":false}',
        'Locked': false,
        'SaveAsDefault': false,
        'AutoCloseOnAck': false,
        'ConfirmOnAutoClose': false,
        'LayoutOpen': false,
        'AutoCloseOnClear': false,
        'ConfirmEventClearOnAutoClose': false,
        'AllowFiltering': false,
        'ShowMaintenanceObject': null,
        'LayoutType': 0,
        'RefreshType': 0,
        'WebLayoutType': null,
        'WidgetsPartitionID': null,
        'ClassType': 'SoftwareHouse.CrossFire.Common.Objects.WebLayout',
        '*routing': null,
        '*ObjectSize': 2991,
        '*id': {
            '_values': [
                5001
            ],
            '_objectTypeName': 'SoftwareHouse.CrossFire.Common.Objects.WebLayout',
            '_appServer': 'VM-INGRTN-16-15',
            'Guid': '98087add-591b-473d-bea2-ae0e663ae03b',
            'RoutingInfo': null,
            'ContextId': '00000000-0000-0000-0000-000000000000',
            'TransactionID': null
        },
        '*PK': [
            'ObjectID'
        ],
        '*state': 1,
        '*appServer': 'VM-INGRTN-16-15',
        '*context': '00000000-0000-0000-0000-000000000000',
        '*container': []
    }
];

const table = [
    {
        'Name': 'Video Monitoring',
        'PartitionID': 1,
        'ObjectID': 1003,
        'LastModifiedByID': 5344,
        'LastModifiedTime': '2022-02-14T08:00:45.617Z',
        'GUID': 'e2a17982-4af8-4d07-9517-b7be6a08db6c',
        'Description': 'Video Monitoring Activity',
        'Template': false,
        'Protected': true,
        'SpecialEditingRequired': false,
        'Panes': '[{"id":1003,"cols":1,"rows":1,"x":0,"y":0,"layerIndex":0,"dataObject":{"guid":"df8fa35c-7253-495a-b72a-6d1d503fbcde","key":"VIDEOMONITORING","icon":"video_call","description":"Video Monitoring Activity","name":"Video Monitoring","loader":{"libPath":"ccure-video-monitor","component":"entry","data":{"Name":"Video Monitoring","translationKey":"VIDEOMONITORING","Description":"Video Monitoring Activity","GUID":"df8fa35c-7253-495a-b72a-6d1d503fbcde","intrinsic":true}}}}]',
        'Options': '{"gridType":"fit","compactType":"none","allowMultiLayer":true,"defaultLayerIndex":0,"baseLayerIndex":1,"maxLayerIndex":2,"pushItems":false,"swap":true,"swapWhileDragging":false,"margin":0,"outerMargin":false,"outerMarginTop":0,"outerMarginRight":0,"outerMarginBottom":0,"outerMarginLeft":0,"useTransformPositioning":true,"mobileBreakpoint":640,"minCols":1,"maxCols":100,"minRows":1,"maxRows":100,"maxItemCols":100,"minItemCols":1,"maxItemRows":100,"minItemRows":1,"maxItemArea":2500,"minItemArea":1,"defaultItemCols":1,"defaultItemRows":1,"fixedColWidth":150,"fixedRowHeight":150,"keepFixedHeightInMobile":false,"keepFixedWidthInMobile":false,"scrollSensitivity":10,"scrollSpeed":20,"enableEmptyCellClick":true,"enableEmptyCellContextMenu":false,"enableEmptyCellDrop":true,"enableEmptyCellDrag":false,"enableOccupiedCellDrop":true,"emptyCellDragMaxCols":50,"emptyCellDragMaxRows":50,"ignoreMarginInRow":false,"draggable":{"enabled":true},"resizable":{"enabled":true},"pushDirections":{"north":true,"east":true,"south":true,"west":true},"disablePushOnDrag":false,"disablePushOnResize":false,"pushResizeItems":true,"displayGrid":"always","disableWindowResize":false,"disableWarnings":false,"scrollToNewItems":false}',
        'Locked': false,
        'SaveAsDefault': false,
        'AutoCloseOnAck': false,
        'ConfirmOnAutoClose': false,
        'LayoutOpen': false,
        'AutoCloseOnClear': false,
        'ConfirmEventClearOnAutoClose': false,
        'AllowFiltering': false,
        'ShowMaintenanceObject': null,
        'LayoutType': 0,
        'RefreshType': 0,
        'WebLayoutType': null,
        'WidgetsPartitionID': null,
        'ClassType': 'SoftwareHouse.CrossFire.Common.Objects.WebLayout',
        '*routing': null,
        '*ObjectSize': 2021,
        '*id': {
            '_values': [
                1003
            ],
            '_objectTypeName': 'SoftwareHouse.CrossFire.Common.Objects.WebLayout',
            '_appServer': 'VM-INGRTN-16-15',
            'Guid': 'e2a17982-4af8-4d07-9517-b7be6a08db6c',
            'RoutingInfo': null,
            'ContextId': '00000000-0000-0000-0000-000000000000',
            'TransactionID': null
        },
        '*PK': [
            'ObjectID'
        ],
        '*state': 1,
        '*appServer': 'VM-INGRTN-16-15',
        '*context': '00000000-0000-0000-0000-000000000000',
        '*container': []
    }
];

export { typeName, table };