const typeName = 'SoftwareHouse.NextGen.Common.SecurityObjects.ApcController';
const schema = {
    'FullClassName': 'SoftwareHouse.NextGen.Common.SecurityObjects.ApcController',
    'LocalizedName': 'apC Controller',
    'IsUserSelectable': true,
    'LocalityType': 'LocalOnly',
    'Description': 'This class is used to specify an apC controller.',
    'IsGroupable': true,
    'PropertyList': [
        {
            'Name': 'Name',
            'LocalizedName': 'Name',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 100,
            'Description': 'apC object name.',
            'IsUdf': false
        },
        {
            'Name': 'Description',
            'LocalizedName': 'Description',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 500,
            'Description': 'Description of this apC Controller.',
            'IsUdf': false
        },
        {
            'Name': 'GUID',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Guid',
            'IsEnum': false,
            'Description': 'Global unique ID.',
            'IsUdf': false
        },
        {
            'Name': 'Address',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'MinValue': 0.0,
            'MaxValue': 2147483647.0,
            'Description': 'The setting of rotary switches as set on the panel.',
            'IsUdf': false
        },
        {
            'Name': 'AddressHexValue',
            'LocalizedName': 'Address',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': false,
            'Type': 'String',
            'IsEnum': false,
            'Description': 'The setting of rotary switches as set on the panel.',
            'LinkedProperties': [
                'Address'
            ],
            'IsUdf': false
        },
        {
            'Name': 'AlwaysUseShuntExpireOutput',
            'LocalizedName': 'Always Use Shunt Expire Output',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'Check whether the Shunt expiration relay should be fired regardless of the shunt time used.',
            'IsUdf': false
        },
        {
            'Name': 'APCType',
            'LocalizedName': 'apC Type',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'SoftwareHouse.NextGen.Common.SecurityObjectDefinitions.APCTypes',
            'IsEnum': true,
            'Description': 'The type of apC panel.',
            'IsUdf': false
        },
        {
            'Name': 'BoardsStateStatus',
            'LocalizedName': 'Boards State Status',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 50,
            'Description': 'Boards state status.',
            'IsUdf': false
        },
        {
            'Name': 'CardNumsViaKP',
            'LocalizedName': 'Card Numbers Via Keypad ',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'Check whether to enter card numbers via keypad or not.',
            'IsUdf': false
        },
        {
            'Name': 'CertificateSigningStatus',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'SoftwareHouse.NextGen.Common.SecurityObjectDefinitions.CertificateSigningRequest',
            'IsEnum': true,
            'Description': 'apC Controller Certificate Signing Status.',
            'IsUdf': false
        },
        {
            'Name': 'ClassType',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': true,
            'Type': 'Type',
            'IsEnum': false,
            'IsUdf': false
        },
        {
            'Name': 'CommFailDelay',
            'LocalizedName': 'Comm Fail Delay (1/10th seconds)',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'MinValue': 0.0,
            'MaxValue': 850.0,
            'Description': 'Panel communication failure delay time 0-850 1/10th second.',
            'IsUdf': false
        },
        {
            'Name': 'CommFailPollPeriod',
            'LocalizedName': 'Comm Fail Poll Period',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'MinValue': 0.0,
            'MaxValue': 999.0,
            'Description': 'Poll period while in communication failure 0-999 1/10th second.',
            'IsUdf': false
        },
        {
            'Name': 'CommunicationStatus',
            'LocalizedName': 'Communication Status',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'SoftwareHouse.NextGen.Common.SecurityObjectDefinitions.ApcCommState',
            'IsEnum': true,
            'Description': 'The communication status of the controller',
            'IsUdf': false
        },
        {
            'Name': 'ConnectionTypeStatus',
            'LocalizedName': 'Connection Type Status',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'SoftwareHouse.NextGen.Common.SecurityObjectDefinitions.apCConnectionTypeStatus',
            'IsEnum': true,
            'Description': 'The connection type status.',
            'IsUdf': false
        },
        {
            'Name': 'ConnectType',
            'LocalizedName': 'Connect Type',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'SoftwareHouse.NextGen.Common.SecurityObjectDefinitions.ConnectTypes',
            'IsEnum': true,
            'Description': 'The communication connection type.',
            'IsUdf': false
        },
        {
            'Name': 'ControllerDefaultPriority',
            'LocalizedName': 'Base Priority for Cause',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'MinValue': 0.0,
            'MaxValue': 255.0,
            'Description': 'Base priority for cause.',
            'IsUdf': false
        },
        {
            'Name': 'ControllerName',
            'LocalizedName': 'Controller Name',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': false,
            'Type': 'String',
            'IsEnum': false,
            'LinkedProperties': [
                'ControllerType'
            ],
            'IsUdf': false
        },
        {
            'Name': 'ControllerRunningStatus',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'MinValue': -2147483648.0,
            'MaxValue': 2147483647.0,
            'Description': 'Controller running status.',
            'IsUdf': false
        },
        {
            'Name': 'ControllerType',
            'LocalizedName': 'Controller Type',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'SoftwareHouse.NextGen.Common.SecurityObjectDefinitions.ControllerTypes',
            'IsEnum': true,
            'Description': 'Type of Controller',
            'IsUdf': false
        },
        {
            'Name': 'CurrentPersonalRecordsStatus',
            'LocalizedName': 'Current Credential Records Status',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'MinValue': -2147483648.0,
            'MaxValue': 2147483647.0,
            'Description': 'Current personnel records status.',
            'IsUdf': false
        },
        {
            'Name': 'DownloadFirmware',
            'LocalizedName': 'Download Firmware',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'SoftwareHouse.NextGen.Common.SecurityObjectDefinitions.DownloadFirmwareRequest',
            'IsEnum': true,
            'Description': 'The status of firmware download.',
            'IsUdf': false
        },
        {
            'Name': 'DownloadStatus',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'MinValue': -2147483648.0,
            'MaxValue': 2147483647.0,
            'Description': 'Status of download.',
            'IsUdf': false
        },
        {
            'Name': 'DuressCodeUsed',
            'LocalizedName': 'Duress Code Used',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'Check whether a duress code is used with this reader or not.',
            'IsUdf': false
        },
        {
            'Name': 'Enabled',
            'LocalizedName': 'Enabled',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'Is this apC online?',
            'IsUdf': false
        },
        {
            'Name': 'FirmwareVersionStatus',
            'LocalizedName': 'Firmware Version Status',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 50,
            'Description': 'Current firmware version.',
            'IsUdf': false
        },
        {
            'Name': 'FolderID',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'MinValue': 1.0,
            'MaxValue': 2147483647.0,
            'Description': 'Hardware folder ID.',
            'IsUdf': false
        },
        {
            'Name': 'GeographicLocation',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': -1,
            'Description': 'Location',
            'IsUdf': false
        },
        {
            'Name': 'GISLocation',
            'LocalizedName': 'GIS Location',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': false,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'Location',
            'LinkedProperties': [
                'GeographicLocation'
            ],
            'IsUdf': false
        },
        {
            'Name': 'HardwareFolderObjectKey',
            'LocalizedName': 'Hardware Folder',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': false,
            'Type': 'ObjectKey',
            'IsEnum': false,
            'Description': 'The name of the hardware folder that this controller is in.',
            'LinkedProperties': [
                'FolderID'
            ],
            'LookupData': {
                'IsQueryable': true,
                'PersistentTypeProperty': '',
                'PersistentIdProperty': 'FolderID',
                'TargetName': 'Name',
                'TargetObjectID': 'ObjectID',
                'ValidLookupTypes': [
                    'SoftwareHouse.NextGen.Common.SecurityObjects.HardwareFolder'
                ]
            },
            'IsUdf': false
        },
        {
            'Name': 'HostCommFailDelay',
            'LocalizedName': 'Host Comm Fail Delay',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Time',
            'IsEnum': false,
            'Description': 'Host communication fail delay time.',
            'DynamicViewColumnType': 'Time',
            'IsUdf': false
        },
        {
            'Name': 'LastModifiedByID',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'MinValue': -2147483648.0,
            'MaxValue': 2147483647.0,
            'Description': 'The ID of the operator that last modified this object.',
            'IsUdf': false
        },
        {
            'Name': 'LastModifiedTime',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'DateTime',
            'IsEnum': false,
            'Description': 'The timestamp of the last modification of this object.',
            'IsUdf': false
        },
        {
            'Name': 'LocationMetaTagFullName',
            'LocalizedName': 'Location Tag Path',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': false,
            'Type': 'String',
            'IsEnum': false,
            'Description': 'Represents the full path name of the objects location tag.',
            'LinkedProperties': null,
            'IsUdf': false
        },
        {
            'Name': 'MaintenanceMode',
            'LocalizedName': 'Maintenance Mode',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'The current Maintenance Mode value for this Apc Controller.',
            'IsUdf': false
        },
        {
            'Name': 'MaxPersonnelRecords',
            'LocalizedName': 'MaxPersonnelRecords',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'MinValue': -2147483648.0,
            'MaxValue': 2147483647.0,
            'Description': 'Maximum personnel records.',
            'IsUdf': false
        },
        {
            'Name': 'NewFirmwareVersion',
            'LocalizedName': 'New Firmware Version',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 50,
            'Description': 'The firmware version',
            'IsUdf': false
        },
        {
            'Name': 'ObjectID',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'MinValue': -2147483648.0,
            'MaxValue': 2147483647.0,
            'Description': 'The Object ID.',
            'IsUdf': false
        },
        {
            'Name': 'ObjectKey',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': false,
            'Type': 'ObjectKey',
            'IsEnum': false,
            'IsUdf': false
        },
        {
            'Name': 'OnlineStatus',
            'LocalizedName': 'Online Status',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'SoftwareHouse.NextGen.Common.SecurityObjectDefinitions.OnlineStatus',
            'IsEnum': true,
            'Description': 'Online status.',
            'IsUdf': false
        },
        {
            'Name': 'PanelFullStatus',
            'LocalizedName': 'Panel Full Status',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'SoftwareHouse.NextGen.Common.SecurityObjectDefinitions.ApcPanelFullStatus',
            'IsEnum': true,
            'Description': 'Panel full status.',
            'IsUdf': false
        },
        {
            'Name': 'PanelNearlyFullStatus',
            'LocalizedName': 'Panel Nearly Full Status',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'SoftwareHouse.NextGen.Common.SecurityObjectDefinitions.ApcPanelNearlyFullStatus',
            'IsEnum': true,
            'Description': 'Panel nearly full status.',
            'IsUdf': false
        },
        {
            'Name': 'PartitionID',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'MinValue': -2147483648.0,
            'MaxValue': 2147483647.0,
            'Description': 'Partition ID.',
            'IsUdf': false
        },
        {
            'Name': 'PartitionKey',
            'LocalizedName': 'Partition Name',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': false,
            'Type': 'ObjectKey',
            'IsEnum': false,
            'Description': 'Partition of object',
            'LinkedProperties': [
                'PartitionID'
            ],
            'LookupData': {
                'IsQueryable': true,
                'PersistentTypeProperty': '',
                'PersistentIdProperty': 'PartitionID',
                'TargetName': 'Name',
                'TargetObjectID': 'ObjectID',
                'ValidLookupTypes': [
                    'SoftwareHouse.CrossFire.Common.Objects.Partition'
                ]
            },
            'IsUdf': false
        },
        {
            'Name': 'PercentFull',
            'LocalizedName': 'Percent Full',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'MinValue': 0.0,
            'MaxValue': 99.0,
            'Description': 'The Percent Full.',
            'IsUdf': false
        },
        {
            'Name': 'PollPeriod',
            'LocalizedName': 'Poll Period (1/10 seconds)',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'MinValue': 0.0,
            'MaxValue': 850.0,
            'Description': 'Poll Period value 0-850 1/10th second.',
            'IsUdf': false
        },
        {
            'Name': 'PortID',
            'LocalizedName': 'Port ID',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'MinValue': -2147483648.0,
            'MaxValue': 2147483647.0,
            'Description': 'The Port ID.',
            'IsUdf': false
        },
        {
            'Name': 'PortKey',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': false,
            'Type': 'ObjectKey',
            'IsEnum': false,
            'Description': 'If you are  configuring a direct-connect apC panel, select the port of which the apC is attached.',
            'LinkedProperties': [
                'PortKey'
            ],
            'IsUdf': false
        },
        {
            'Name': 'Protected',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'Whether this apC Controller record is protected from deletion in the database or not.',
            'IsUdf': false
        },
        {
            'Name': 'RMLCDMessageSetID',
            'LocalizedName': 'RM LCD Message Set',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'MinValue': 0.0,
            'MaxValue': 2147483647.0,
            'Description': 'The Database record id for the RM Reader LCD Message Set',
            'IsUdf': false
        },
        {
            'Name': 'RMLCDMessageSetObjectKey',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': false,
            'Type': 'ObjectKey',
            'IsEnum': false,
            'Description': 'RM LCD Message Set for controller',
            'LinkedProperties': [
                'RMLCDMessageSetID'
            ],
            'LookupData': {
                'IsQueryable': true,
                'PersistentTypeProperty': '',
                'PersistentIdProperty': 'RMLCDMessageSetID',
                'TargetName': 'Name',
                'TargetObjectID': 'ObjectID',
                'ValidLookupTypes': [
                    'SoftwareHouse.NextGen.Common.SecurityObjects.RMReaderLCDMessageSet'
                ]
            },
            'IsUdf': false
        },
        {
            'Name': 'Template',
            'LocalizedName': 'Template',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'Is this a template?',
            'IsUdf': false
        },
        {
            'Name': 'TimeZone',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'MinValue': -2147483648.0,
            'MaxValue': 2147483647.0,
            'Description': 'The time zone for this apC Controller.',
            'IsUdf': false
        },
        {
            'Name': 'TimeZoneKey',
            'LocalizedName': 'Time Zone',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': false,
            'Type': 'ObjectKey',
            'IsEnum': false,
            'Description': 'Specify a time zone for the apC panel. ',
            'LinkedProperties': [
                'TimeZone'
            ],
            'LookupData': {
                'IsQueryable': true,
                'PersistentTypeProperty': '',
                'PersistentIdProperty': 'TimeZone',
                'TargetName': 'Name',
                'TargetObjectID': 'ObjectID',
                'ValidLookupTypes': [
                    'SoftwareHouse.CrossFire.Common.Objects.TimeZone'
                ]
            },
            'IsUdf': false
        },
        {
            'Name': 'TotalRAM',
            'LocalizedName': 'TotalRAM',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'MinValue': -2147483648.0,
            'MaxValue': 2147483647.0,
            'Description': 'Total RAM size.',
            'IsUdf': false
        },
        {
            'Name': 'WaitTime',
            'LocalizedName': 'Wait Time',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'MinValue': 0.0,
            'MaxValue': 999.0,
            'Description': 'Poll timeout delay time 0-999 1/10th second.',
            'IsUdf': false
        }
    ]
};

export { typeName, schema };