const typeName = 'SoftwareHouse.NextGen.Common.SecurityObjects.iStarController';
const schema = {
    'FullClassName': 'SoftwareHouse.NextGen.Common.SecurityObjects.iStarController',
    'LocalizedName': 'iSTAR Controller',
    'IsUserSelectable': true,
    'LocalityType': 'LocalOnly',
    'Description': 'This class is used to specify an iSTAR controller in the system.',
    'IsGroupable': true,
    'PropertyList': [
        {
            'Name': 'Name',
            'LocalizedName': 'Name',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 100,
            'Description': 'The name of this iSTAR controller.',
            'IsUdf': false
        },
        {
            'Name': 'Description',
            'LocalizedName': 'Description',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 500,
            'Description': 'The description of this iSTAR controller.',
            'IsUdf': false
        },
        {
            'Name': 'GUID',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Guid',
            'IsEnum': false,
            'Description': 'The GUID of this iSTAR controller.',
            'IsUdf': false
        },
        {
            'Name': 'DriverOwnerGUID',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': true,
            'Type': 'Guid',
            'IsEnum': false,
            'Description': 'The GUID of the iStar driver to which this controller belongs',
            'IsUdf': false
        },
        {
            'Name': 'ActualBoardTypeStatus',
            'LocalizedName': 'Actual Board Type Status',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'SoftwareHouse.NextGen.Common.SecurityObjectDefinitions.iStarTypes',
            'IsEnum': true,
            'Description': 'The actual board type status of this iSTAR controller.',
            'IsUdf': false
        },
        {
            'Name': 'AutomaticDoorUnlockControl',
            'LocalizedName': 'Automatic Door Unlock Control',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'If checked, while the door is open, then when the RTE is activated or a card is presented (or a momentary unlock occurs), the strike will be activated for the unlock time, otherwise the strike will not be activated.',
            'IsUdf': false
        },
        {
            'Name': 'AutomaticDownloadFlag',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'Download automatically',
            'IsUdf': false
        },
        {
            'Name': 'AvailableDatabaseRAMSizeStatus',
            'LocalizedName': 'Available database RAM size status',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'MinValue': -2147483648.0,
            'MaxValue': 2147483647.0,
            'Description': 'The free physical memory in KB for this iSTAR controller.',
            'IsUdf': false
        },
        {
            'Name': 'AvailableProgramRAMSizeStatus',
            'LocalizedName': 'Available program RAM size status',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'MinValue': -2147483648.0,
            'MaxValue': 2147483647.0,
            'Description': 'The amount of available program memory in KB for this iSTAR controller.',
            'IsUdf': false
        },
        {
            'Name': 'AvailableRAMSizeStatus',
            'LocalizedName': 'Available RAM size status',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'MinValue': -2147483648.0,
            'MaxValue': 2147483647.0,
            'Description': 'The free physical memory in KB for this iSTAR controller.',
            'IsUdf': false
        },
        {
            'Name': 'BackupImageVersionStatus',
            'LocalizedName': 'Backup image version status',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 100,
            'Description': 'The status of the backup image version for this iSTAR controller.',
            'IsUdf': false
        },
        {
            'Name': 'Baudrate',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'MinValue': 0.0,
            'MaxValue': 2147483647.0,
            'Description': 'Baudrate for communication.',
            'IsUdf': false
        },
        {
            'Name': 'BluetoothEnabled',
            'LocalizedName': 'Bluetooth Enabled',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'Allow use of Bluetooth Service Tool for this controller.',
            'IsUdf': false
        },
        {
            'Name': 'BoardsStateStatus',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 50,
            'Description': 'Boards State Status.',
            'IsUdf': false
        },
        {
            'Name': 'BoardTypeStatus',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'MinValue': -2147483648.0,
            'MaxValue': 2147483647.0,
            'Description': 'Board Type Status.',
            'IsUdf': false
        },
        {
            'Name': 'BootLoaderVersionStatus',
            'LocalizedName': 'Boot loader version status',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 100,
            'Description': 'The current status of the boot loader version for this iSTAR controller.',
            'IsUdf': false
        },
        {
            'Name': 'CardFormatID',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'MinValue': 1.0,
            'MaxValue': 2147483647.0,
            'Description': '*** iStarControllerCardFormatIDToolTipText ***',
            'IsUdf': false
        },
        {
            'Name': 'CardFormatKey',
            'LocalizedName': 'Card Format Name',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': false,
            'Type': 'ObjectKey',
            'IsEnum': false,
            'Description': 'The Card Format used by the Personnel Group when in offline mode',
            'LinkedProperties': [
                'CardFormatID'
            ],
            'LookupData': {
                'IsQueryable': true,
                'PersistentTypeProperty': '',
                'PersistentIdProperty': 'CardFormatID',
                'TargetName': 'Name',
                'TargetObjectID': 'ObjectID',
                'ValidLookupTypes': [
                    'SoftwareHouse.NextGen.Common.SecurityObjects.CardFormat'
                ]
            },
            'IsUdf': false
        },
        {
            'Name': 'CertificateCreatedTime',
            'LocalizedName': 'Certificate created time',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'DateTime',
            'IsEnum': false,
            'Description': 'This is the timestamp when the certificate is created.',
            'IsUdf': false
        },
        {
            'Name': 'CertificateExpiringTime',
            'LocalizedName': 'Certificate expiring time',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'DateTime',
            'IsEnum': false,
            'Description': 'This is the timestamp when the certificate is expired.',
            'IsUdf': false
        },
        {
            'Name': 'CertificateSigningStatus',
            'LocalizedName': 'Certificate signing status',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'SoftwareHouse.NextGen.Common.SecurityObjectDefinitions.CertificateSigningRequest',
            'IsEnum': true,
            'Description': 'The current status of certificate signing for this iSTAR controller.',
            'IsUdf': false
        },
        {
            'Name': 'ClassType',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': true,
            'Type': 'Type',
            'IsEnum': false,
            'IsUdf': false
        },
        {
            'Name': 'ClusterID',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'MinValue': 1.0,
            'MaxValue': 2147483647.0,
            'Description': 'The iSTAR cluster\'s object ID.',
            'IsUdf': false
        },
        {
            'Name': 'ClusterKey',
            'LocalizedName': 'Cluster',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': false,
            'Type': 'ObjectKey',
            'IsEnum': false,
            'Description': 'The object key of the iSTAR cluster associated with this iSTAR controller.',
            'LinkedProperties': [
                'ClusterID'
            ],
            'LookupData': {
                'IsQueryable': true,
                'PersistentTypeProperty': '',
                'PersistentIdProperty': 'ClusterID',
                'TargetName': 'Name',
                'TargetObjectID': 'ObjectID',
                'ValidLookupTypes': [
                    'SoftwareHouse.NextGen.Common.SecurityObjects.Cluster'
                ]
            },
            'IsUdf': false
        },
        {
            'Name': 'Com1Protocol',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'SoftwareHouse.NextGen.Common.SecurityObjectDefinitions.IStar3ComProtocol',
            'IsEnum': true,
            'Description': 'The protocol of Com 1.',
            'IsUdf': false
        },
        {
            'Name': 'Com2Protocol',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'SoftwareHouse.NextGen.Common.SecurityObjectDefinitions.IStar3ComProtocol',
            'IsEnum': true,
            'Description': 'The protocol of Com 2.',
            'IsUdf': false
        },
        {
            'Name': 'CommunicationMode',
            'LocalizedName': 'Communication Mode',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'SoftwareHouse.NextGen.Common.SecurityObjectDefinitions.IPAddressFamily',
            'IsEnum': true,
            'Description': 'iStar Communication Mode: IPV4 or IPV6',
            'IsUdf': false
        },
        {
            'Name': 'CommunicationRole',
            'LocalizedName': 'Communication Role',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': false,
            'Type': 'SoftwareHouse.NextGen.Common.SecurityObjects.iStarController+CommunicationRoles',
            'IsEnum': true,
            'Description': 'This property is used mainly to associate a CommMethod with the right controller when it is exported/imported.',
            'LinkedProperties': [
                'ObjectID'
            ],
            'IsUdf': false
        },
        {
            'Name': 'CommunicationsPathStatus',
            'LocalizedName': 'Communications Path Status',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'SoftwareHouse.NextGen.Common.SecurityObjectDefinitions.iStarCommPath',
            'IsEnum': true,
            'Description': 'The current communication path status for this iSTAR controller.',
            'IsUdf': false
        },
        {
            'Name': 'CommunicationStateStatus',
            'LocalizedName': 'Communication State Status',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'SoftwareHouse.NextGen.Common.SecurityObjectDefinitions.iStarCommState',
            'IsEnum': true,
            'Description': 'The current communication state status for this iSTAR controller.',
            'IsUdf': false
        },
        {
            'Name': 'ConnectionPathStatus',
            'LocalizedName': 'Connection path status',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'SoftwareHouse.NextGen.Common.SecurityObjectDefinitions.iStarConnType',
            'IsEnum': true,
            'Description': 'The current connection path status for this iSTAR controller.',
            'IsUdf': false
        },
        {
            'Name': 'ControllerDownloadTime',
            'LocalizedName': 'Controller Boot Time',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'DateTime',
            'IsEnum': false,
            'Description': 'The boot time of the iSTAR Controller.',
            'DateTimeKind': 'Local',
            'DynamicViewColumnType': 'UTCDateTime',
            'IsUdf': false
        },
        {
            'Name': 'ControllerName',
            'LocalizedName': 'Controller Name',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': false,
            'Type': 'String',
            'IsEnum': false,
            'LinkedProperties': [
                'ControllerType'
            ],
            'IsUdf': false
        },
        {
            'Name': 'ControllerType',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'SoftwareHouse.NextGen.Common.SecurityObjectDefinitions.ControllerTypes',
            'IsEnum': true,
            'Description': 'The type of the controller.',
            'IsUdf': false
        },
        {
            'Name': 'ControllerTypeStatus',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'SoftwareHouse.NextGen.Common.SecurityObjectDefinitions.iStarControllerType',
            'IsEnum': true,
            'Description': 'Controller Type Status.',
            'IsUdf': false
        },
        {
            'Name': 'CPUNameStatus',
            'LocalizedName': 'CPU Name Status',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 100,
            'Description': 'CPU name status.',
            'IsUdf': false
        },
        {
            'Name': 'CurrentPersonalRecordsStatus',
            'LocalizedName': 'Current Credential Records Status',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'MinValue': -2147483648.0,
            'MaxValue': 2147483647.0,
            'Description': 'The current status of current personnel records for this iSTAR controller.',
            'IsUdf': false
        },
        {
            'Name': 'CurrentPersonnelRecord',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'MinValue': -2147483648.0,
            'MaxValue': 2147483647.0,
            'Description': 'The current personnel\'s record.',
            'IsUdf': false
        },
        {
            'Name': 'DatabaseRAMSizeStatus',
            'LocalizedName': 'Database RAM size status',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'MinValue': -2147483648.0,
            'MaxValue': 2147483647.0,
            'Description': 'The total physical memory in KB for this iSTAR controller.',
            'IsUdf': false
        },
        {
            'Name': 'DefaultGateway1Status',
            'LocalizedName': 'Default Gateway 1 Status',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 100,
            'Description': 'Default Gateway (Ethernet Adapter 1)',
            'IsUdf': false
        },
        {
            'Name': 'DefaultGateway2Status',
            'LocalizedName': 'Default Gateway 2 Status',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 100,
            'Description': 'Default Gateway (Ethernet Adapter 2)',
            'IsUdf': false
        },
        {
            'Name': 'DeviceType',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'MinValue': 0.0,
            'MaxValue': 2147483647.0,
            'Description': 'Device type of this controller.',
            'IsUdf': false
        },
        {
            'Name': 'DisplayableIEEE8021xCertificateCreatedTime',
            'LocalizedName': '802.1x Certificate created time',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': false,
            'Type': 'String',
            'IsEnum': false,
            'Description': 'The timestamp that the 802.1x certificate was created.',
            'LinkedProperties': [
                'IEEE8021xCertificateCreatedTime'
            ],
            'IsUdf': false
        },
        {
            'Name': 'DisplayableIEEE8021xCertificateExpiringTime',
            'LocalizedName': '802.1x Certificate expiring time',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': false,
            'Type': 'String',
            'IsEnum': false,
            'Description': 'The timestamp that the 802.1x certificate will expire.',
            'LinkedProperties': [
                'IEEE8021xCertificateExpiringTime'
            ],
            'IsUdf': false
        },
        {
            'Name': 'DisplayableWebCertificateCreatedTime',
            'LocalizedName': 'Web Certificate created time',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': false,
            'Type': 'String',
            'IsEnum': false,
            'Description': 'The timestamp that the Web certificate was created.',
            'LinkedProperties': [
                'WebCertificateCreatedTime'
            ],
            'IsUdf': false
        },
        {
            'Name': 'DisplayableWebCertificateExpiringTime',
            'LocalizedName': 'Web Certificate expiring time',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': false,
            'Type': 'String',
            'IsEnum': false,
            'Description': 'The timestamp that the Web certificate will expire.',
            'LinkedProperties': [
                'WebCertificateExpiringTime'
            ],
            'IsUdf': false
        },
        {
            'Name': 'DNSQuerySuffix1Status',
            'LocalizedName': 'DNS Query Suffix 1 Status',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 100,
            'Description': 'DNS Query Suffix for Ethernet Adapter 1',
            'IsUdf': false
        },
        {
            'Name': 'DNSQuerySuffix2Status',
            'LocalizedName': 'DNS Query Suffix 2 Status',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 100,
            'Description': 'DNS Query Suffix for Ethernet Adapter 2',
            'IsUdf': false
        },
        {
            'Name': 'DownloadCardWOClearance',
            'LocalizedName': 'Download Card Without Clearance',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'Download Card Without Clearance',
            'IsUdf': false
        },
        {
            'Name': 'DownloadFirmware',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'SoftwareHouse.NextGen.Common.SecurityObjectDefinitions.DownloadFirmwareRequest',
            'IsEnum': true,
            'Description': 'Download firmware.',
            'IsUdf': false
        },
        {
            'Name': 'EdgeModelStatus',
            'LocalizedName': 'Edge Door Model Status',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'SoftwareHouse.NextGen.Common.SecurityObjectDefinitions.iStarEdgeModel',
            'IsEnum': true,
            'Description': 'The current Edge model status',
            'IsUdf': false
        },
        {
            'Name': 'eMMCHealthStatus',
            'LocalizedName': 'eMMC Health Status (%)',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'Description': 'The current value of the eMMC Health Status for this Edge G2 Controller.',
            'DynamicViewColumnType': 'General',
            'IsUdf': false
        },
        {
            'Name': 'Enabled',
            'LocalizedName': 'Enabled',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'Check whether this iSTAR controller is enabled or not.',
            'IsUdf': false
        },
        {
            'Name': 'EnableFICAMHighAssurance',
            'LocalizedName': 'Enable FICAM High Assurance',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'Enable FICAM High Assurance',
            'IsUdf': false
        },
        {
            'Name': 'EnableWebPage',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'Enable Web Page',
            'IsUdf': false
        },
        {
            'Name': 'EncryptionLevelStatus',
            'LocalizedName': 'Encryption Level Status',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'SoftwareHouse.NextGen.Common.SecurityObjectDefinitions.EncryptionLevel',
            'IsEnum': true,
            'Description': 'The current encryption level status for this iSTAR controller.',
            'IsUdf': false
        },
        {
            'Name': 'EncryptionSettingStatus',
            'LocalizedName': 'Encryption Setting Status',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'SoftwareHouse.NextGen.Common.SecurityObjectDefinitions.EncryptionSettingValue',
            'IsEnum': true,
            'Description': 'Controller Encryption Setting',
            'IsUdf': false
        },
        {
            'Name': 'EstimateMaxPersonnelRecordAllowed',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'MinValue': -2147483648.0,
            'MaxValue': 2147483647.0,
            'Description': 'Estimate Max Personnel Record Allowed.',
            'IsUdf': false
        },
        {
            'Name': 'FastDownloadPriority',
            'LocalizedName': 'Fast Download Priority',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'SoftwareHouse.NextGen.Common.SecurityObjectDefinitions.FastDownloadPriorityType',
            'IsEnum': true,
            'Description': 'Personnel Fast Download Priority',
            'IsUdf': false
        },
        {
            'Name': 'FastDownloadThreshold',
            'LocalizedName': 'Fast Download Threshold',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'MinValue': 100.0,
            'MaxValue': 100000.0,
            'Description': 'Personnel Fast Download Threshold',
            'IsUdf': false
        },
        {
            'Name': 'FipsMode',
            'LocalizedName': 'Fips Mode',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'SoftwareHouse.NextGen.Common.SecurityObjectDefinitions.EncryptionLevel',
            'IsEnum': true,
            'Description': 'The Fips Mode for encryption',
            'IsUdf': false
        },
        {
            'Name': 'FirmwareRequestType',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'SoftwareHouse.NextGen.Common.SecurityObjectDefinitions.FirmwareDownloadType',
            'IsEnum': true,
            'Description': 'Firmware Download Request Type',
            'IsUdf': false
        },
        {
            'Name': 'FirmwareVersionStatus',
            'LocalizedName': 'Firmware Version Status',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 50,
            'Description': 'The firmware version of this iSTAR controller.',
            'IsUdf': false
        },
        {
            'Name': 'GeographicLocation',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': -1,
            'Description': 'Location',
            'IsUdf': false
        },
        {
            'Name': 'GISLocation',
            'LocalizedName': 'GIS Location',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': false,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'Location',
            'LinkedProperties': [
                'GeographicLocation'
            ],
            'IsUdf': false
        },
        {
            'Name': 'HostIPAddressStatus',
            'LocalizedName': 'Host IP Address Status',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 100,
            'Description': 'IP Address of Host as reported back from the panel',
            'IsUdf': false
        },
        {
            'Name': 'IEEE8021xCertificateCreatedTime',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'DateTime',
            'IsEnum': false,
            'Description': 'The timestamp that the 802.1x certificate was created.',
            'DateTimeKind': 'Local',
            'DynamicViewColumnType': 'DateTime',
            'IsUdf': false
        },
        {
            'Name': 'IEEE8021xCertificateExpiringTime',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'DateTime',
            'IsEnum': false,
            'Description': 'The timestamp that the 802.1x certificate will expire.',
            'DateTimeKind': 'Local',
            'DynamicViewColumnType': 'DateTime',
            'IsUdf': false
        },
        {
            'Name': 'IPACMLatencyThreshold',
            'LocalizedName': 'IP-ACM Latency Threshold',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'Description': 'The length of time in milliseconds in a roundtrip that must transpire before an IP-ACM High Latency Alarm is declared.',
            'IsUdf': false
        },
        {
            'Name': 'IPAddress',
            'LocalizedName': 'IP Address',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 100,
            'Description': 'Static Onboard NIC IP Address 1',
            'IsUdf': false
        },
        {
            'Name': 'IPAddress1Status',
            'LocalizedName': 'IP Address 1 Status',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 100,
            'Description': 'The current status for IPAddress1 for this iSTAR controller.',
            'IsUdf': false
        },
        {
            'Name': 'IPAddress2',
            'LocalizedName': 'IP Address 2',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 100,
            'Description': 'Static Onboard NIC IP Address 2',
            'IsUdf': false
        },
        {
            'Name': 'IPAddress2Status',
            'LocalizedName': 'IP Address 2 Status',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 100,
            'Description': 'The current status for IPAddress 2 for this iSTAR controller.',
            'IsUdf': false
        },
        {
            'Name': 'IsTLS13',
            'LocalizedName': 'In TLS 1.3 Cluster',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': false,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'Whether this controller is in a TLS 1.3 cluster or not',
            'LinkedProperties': [
                'ClusterKey'
            ],
            'IsUdf': false
        },
        {
            'Name': 'IsUltraG2',
            'LocalizedName': 'Is Ultra G2',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'Whether this iSTAR Ultra controller is in G2 Mode or not',
            'IsUdf': false
        },
        {
            'Name': 'LastFastDownloadTime',
            'LocalizedName': 'Last Fast Download Time',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'DateTime',
            'IsEnum': false,
            'Description': 'Controller last successful fast download time',
            'DateTimeKind': 'Local',
            'DynamicViewColumnType': 'DateTime',
            'IsUdf': false
        },
        {
            'Name': 'LastFirmwareInstallationStatus',
            'LocalizedName': 'Last Firmware Installation Status',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'SoftwareHouse.NextGen.Common.SecurityObjectDefinitions.FirmwareInstallation',
            'IsEnum': true,
            'Description': 'The status that the last time firmware installed',
            'IsUdf': false
        },
        {
            'Name': 'LastFirmwareInstallationTime',
            'LocalizedName': 'Last Firmware Installation Time',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'DateTime',
            'IsEnum': false,
            'Description': 'The timestamp that the last time firmware installed',
            'IsUdf': false
        },
        {
            'Name': 'LastModifiedByID',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'MinValue': 1.0,
            'MaxValue': 2147483647.0,
            'Description': 'Last Modified By ID.',
            'IsUdf': false
        },
        {
            'Name': 'LastModifiedTime',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'DateTime',
            'IsEnum': false,
            'Description': 'Last Modified Time.',
            'DateTimeKind': 'Local',
            'DynamicViewColumnType': 'DateTime',
            'IsUdf': false
        },
        {
            'Name': 'LEDLCDPowerOff',
            'LocalizedName': 'Power Suppression',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'Turn off LEDs and LCD Backlight',
            'IsUdf': false
        },
        {
            'Name': 'LocationMetaTagFullName',
            'LocalizedName': 'Location Tag Path',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': false,
            'Type': 'String',
            'IsEnum': false,
            'Description': 'Represents the full path name of the objects location tag.',
            'LinkedProperties': null,
            'IsUdf': false
        },
        {
            'Name': 'LockHostIPAddress',
            'LocalizedName': 'Lock Host IPAddress',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'Host IP Address Locked on Controller',
            'IsUdf': false
        },
        {
            'Name': 'LockIPAddress1Status',
            'LocalizedName': 'Lock IPAddress 1 Status',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'Controller IP Address 1 Locked',
            'IsUdf': false
        },
        {
            'Name': 'LockIPAddress2Status',
            'LocalizedName': 'LockI PAddress 2 Status',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'Controller IP Address 2 Locked',
            'IsUdf': false
        },
        {
            'Name': 'MACAddress',
            'LocalizedName': 'MAC Address',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 100,
            'Description': 'Enter the unique MAC address of this iSTAR controller.  The format of a valid MAC address is 0050F9xxxxxx, where x is 0-9 or a-f.',
            'IsUdf': false
        },
        {
            'Name': 'MaintenanceMode',
            'LocalizedName': 'Maintenance Mode',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'The current Maintenance Mode value for this iStar Controller.',
            'IsUdf': false
        },
        {
            'Name': 'MonitorState',
            'LocalizedName': 'Monitor State',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': false,
            'Type': 'SoftwareHouse.NextGen.Common.SecurityObjectDefinitions.IStarControllerMonitorState',
            'IsEnum': true,
            'Description': 'The current monitor state of this iSTAR controller.',
            'LinkedProperties': [
                'Enabled',
                'CommunicationStateStatus',
                'PanelStateStatus',
                'OnlineStatus'
            ],
            'IsUdf': false
        },
        {
            'Name': 'NATAddressUse',
            'LocalizedName': 'Use NATAddress',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'NAT used',
            'IsUdf': false
        },
        {
            'Name': 'NATIPAddress',
            'LocalizedName': 'NAT IPAddress Status',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 100,
            'Description': 'NAT IP Address',
            'IsUdf': false
        },
        {
            'Name': 'NetBIOSName',
            'LocalizedName': 'NetBIOS Name',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 100,
            'Description': 'NET BIOS Name',
            'IsUdf': false
        },
        {
            'Name': 'NewFirmwareVersion',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 50,
            'Description': 'The firmware version',
            'IsUdf': false
        },
        {
            'Name': 'NumberOfACMStatus',
            'LocalizedName': 'Number of ACM Status',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'MinValue': 0.0,
            'MaxValue': 2147483647.0,
            'Description': 'The current status for number of ACM for this iSTAR controller.',
            'IsUdf': false
        },
        {
            'Name': 'ObjectID',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'MinValue': -2147483648.0,
            'MaxValue': 2147483647.0,
            'Description': 'The object ID of this controller.',
            'IsUdf': false
        },
        {
            'Name': 'ObjectKey',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': false,
            'Type': 'ObjectKey',
            'IsEnum': false,
            'IsUdf': false
        },
        {
            'Name': 'OfflineModeDaysToKeepCredential',
            'LocalizedName': 'Number of Days to Keep Credentials in Offline Mode',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'Description': 'The number of days to keep credentials in offline mode. 0 means do not keep credentials.  The valid range is 0-9999.',
            'IsUdf': false
        },
        {
            'Name': 'OfflineModeNumberOfAdmittedCards',
            'LocalizedName': 'Number of Last Admitted Cards to Admit when in Offline Mode',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'MinValue': 0.0,
            'MaxValue': 1000.0,
            'Description': 'The number of the last admitted cards to admit when the IP-ACMs are in offline mode.',
            'IsUdf': false
        },
        {
            'Name': 'OfflineModePersonnelGroupID',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'Description': 'The personnel Group to allow admittance when the IP-ACM goes into offline mode.',
            'IsUdf': false
        },
        {
            'Name': 'OfflineModePersonnelGroupKey',
            'LocalizedName': 'Personnel Group to Admit while in Offline Mode',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': false,
            'Type': 'ObjectKey',
            'IsEnum': false,
            'Description': 'The personnel group to admit while IP-ACMs are in offline mode',
            'LinkedProperties': [
                'OfflineModePersonnelGroupID'
            ],
            'LookupData': {
                'IsQueryable': true,
                'PersistentTypeProperty': '',
                'PersistentIdProperty': 'OfflineModePersonnelGroupID',
                'TargetName': 'Name',
                'TargetObjectID': 'ObjectID',
                'ValidLookupTypes': [
                    'SoftwareHouse.CrossFire.Common.Objects.Group'
                ]
            },
            'IsUdf': false
        },
        {
            'Name': 'OfflineModeWaitTime',
            'LocalizedName': 'Wait Time before in Offline Mode',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'Description': 'The time in seconds to wait before entering Offline line when communication is lost with the GCM Board.',
            'IsUdf': false
        },
        {
            'Name': 'OnBoardReaderLEDControl',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'SoftwareHouse.NextGen.Common.SecurityObjectDefinitions.iStarEdgeControllerOnboardReaderLEDControl',
            'IsEnum': true,
            'Description': 'Onboard Reader LED control',
            'IsUdf': false
        },
        {
            'Name': 'OnlineStatus',
            'LocalizedName': 'Online Status',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'SoftwareHouse.NextGen.Common.SecurityObjectDefinitions.OnlineStatus',
            'IsEnum': true,
            'Description': 'Online Status',
            'IsUdf': false
        },
        {
            'Name': 'OwningDriverKey',
            'LocalizedName': 'Owner Driver',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': false,
            'Type': 'ObjectKey',
            'IsEnum': false,
            'Description': 'The driver that the controller communicate with',
            'LinkedProperties': [
                'DriverOwnerGUID'
            ],
            'LookupData': {
                'IsQueryable': true,
                'PersistentTypeProperty': '',
                'PersistentIdProperty': 'DriverOwnerGUID',
                'TargetName': 'Address',
                'TargetObjectID': 'DriverGuid',
                'ValidLookupTypes': [
                    'SoftwareHouse.CrossFire.Common.Objects.BaseDriverStatus'
                ]
            },
            'IsUdf': false
        },
        {
            'Name': 'PanelStateStatus',
            'LocalizedName': 'Panel State Status',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'SoftwareHouse.NextGen.Common.SecurityObjectDefinitions.PanelState',
            'IsEnum': true,
            'Description': 'The current status for panel state for this iSTAR controller.',
            'IsUdf': false
        },
        {
            'Name': 'PartitionID',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'MinValue': 1.0,
            'MaxValue': 2147483647.0,
            'Description': 'The partition ID of this iSTAR controller.',
            'IsUdf': false
        },
        {
            'Name': 'PartitionKey',
            'LocalizedName': 'Partition Name',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': false,
            'Type': 'ObjectKey',
            'IsEnum': false,
            'Description': 'Partition of object',
            'LinkedProperties': [
                'PartitionID'
            ],
            'LookupData': {
                'IsQueryable': true,
                'PersistentTypeProperty': '',
                'PersistentIdProperty': 'PartitionID',
                'TargetName': 'Name',
                'TargetObjectID': 'ObjectID',
                'ValidLookupTypes': [
                    'SoftwareHouse.CrossFire.Common.Objects.Partition'
                ]
            },
            'IsUdf': false
        },
        {
            'Name': 'Password',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 32,
            'Description': '*** iStarControllerPasswordToolTipText ***',
            'IsUdf': false
        },
        {
            'Name': 'PCMCIAInstalled',
            'LocalizedName': 'PCMCIA Installed',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'Check whether or not the PCMCIA adapter is installed for this iSTAR controller.',
            'IsUdf': false
        },
        {
            'Name': 'PCMCIAIPAddress',
            'LocalizedName': 'PCMCIA IP Address',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 100,
            'Description': 'Enter the unique IP address for the PCMCIA ethernet adapter for this iSTAR controller.',
            'IsUdf': false
        },
        {
            'Name': 'PCMCIAUseDHCP',
            'LocalizedName': 'PCMCIA Use DHCP',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'Check whether to use DHCP to obtain the IP address for the PCMCIA ethernet adapter for this iSTAR controller.',
            'IsUdf': false
        },
        {
            'Name': 'PoEBoardInstalled',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'PoE Board Installed',
            'IsUdf': false
        },
        {
            'Name': 'PrimaryCommunicationStatus',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': true,
            'Type': 'SoftwareHouse.NextGen.Common.SecurityObjectDefinitions.OnlineStatus',
            'IsEnum': true,
            'Description': 'Primary communication status of this iSTAR controller.',
            'IsUdf': false
        },
        {
            'Name': 'PrimaryDNSServer1Status',
            'LocalizedName': 'Primary DNS 1 Status',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 100,
            'Description': 'Primary DNS Server (Ethernet Adapter 1)',
            'IsUdf': false
        },
        {
            'Name': 'PrimaryDNSServer2Status',
            'LocalizedName': 'Primary DNS 2 Status',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 100,
            'Description': 'Primary DNS Server (Ethernet Adapter 2)',
            'IsUdf': false
        },
        {
            'Name': 'PrimaryEthernet',
            'LocalizedName': 'Primary Ethernet',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'Use PCMCIA as Primary NIC',
            'IsUdf': false
        },
        {
            'Name': 'ProcessorTemperatureStatus',
            'LocalizedName': 'Processor Temperature Status (°C)',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'Description': 'The current value of the Processor Temperature Status for this Edge G2 Controller.',
            'DynamicViewColumnType': 'General',
            'IsUdf': false
        },
        {
            'Name': 'ProgramRAMSizeStatus',
            'LocalizedName': 'Program RAM size status',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'MinValue': -2147483648.0,
            'MaxValue': 2147483647.0,
            'Description': 'The total program memory in KB for this iSTAR controller.',
            'IsUdf': false
        },
        {
            'Name': 'Protected',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'Whether this iSTAR controller record is protected from deletion in the database or not.',
            'IsUdf': false
        },
        {
            'Name': 'RAMSizeStatus',
            'LocalizedName': 'RAM Size Status',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'MinValue': -2147483648.0,
            'MaxValue': 2147483647.0,
            'Description': 'The total storage memory in KB for this iSTAR controller.',
            'IsUdf': false
        },
        {
            'Name': 'ReaderSecurityKeyStatus',
            'LocalizedName': 'Reader security key status',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'SoftwareHouse.NextGen.Common.SecurityObjectDefinitions.ReaderSecurityKey',
            'IsEnum': true,
            'Description': 'The current reader security key status',
            'IsUdf': false
        },
        {
            'Name': 'ReaderUSBKey',
            'LocalizedName': 'Reader USB Key',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 100,
            'Description': 'Reader USB Key',
            'IsUdf': false
        },
        {
            'Name': 'ResistorConfig',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'SoftwareHouse.NextGen.Common.SecurityObjectDefinitions.ResistorConfiguration',
            'IsEnum': true,
            'Description': 'Set the supervising resistor configuration.',
            'IsUdf': false
        },
        {
            'Name': 'RMLCDMessageSetID',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'MinValue': 0.0,
            'MaxValue': 2147483647.0,
            'Description': 'RM LCD message set.',
            'IsUdf': false
        },
        {
            'Name': 'RMLCDMessageSetObjectKey',
            'LocalizedName': 'RM LCD Message Set Name',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': false,
            'Type': 'ObjectKey',
            'IsEnum': false,
            'Description': 'RM LCD Message Set for controller',
            'LinkedProperties': [
                'RMLCDMessageSetID'
            ],
            'LookupData': {
                'IsQueryable': true,
                'PersistentTypeProperty': '',
                'PersistentIdProperty': 'RMLCDMessageSetID',
                'TargetName': 'Name',
                'TargetObjectID': 'ObjectID',
                'ValidLookupTypes': [
                    'SoftwareHouse.NextGen.Common.SecurityObjects.RMReaderLCDMessageSet'
                ]
            },
            'IsUdf': false
        },
        {
            'Name': 'SDCardEncryptionStatus',
            'LocalizedName': 'SD Card Encryption Status',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': true,
            'Type': 'SoftwareHouse.NextGen.Common.SecurityObjectDefinitions.SDCardEncryptionStatusType',
            'IsEnum': true,
            'Description': 'iStar Controller SD Card Encryption Status',
            'IsUdf': false
        },
        {
            'Name': 'SDCardInstalledStatus',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'SD Memory Card Installed',
            'IsUdf': false
        },
        {
            'Name': 'SecondaryCommunicationStatus',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': true,
            'Type': 'SoftwareHouse.NextGen.Common.SecurityObjectDefinitions.OnlineStatus',
            'IsEnum': true,
            'Description': 'Secondary communication status for this iSTAR controller.',
            'IsUdf': false
        },
        {
            'Name': 'SecondaryDNSServer1Status',
            'LocalizedName': 'Secondary DNS 1 Status',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 100,
            'Description': 'Secondary DNS Server (Ethernet Adapter 1)',
            'IsUdf': false
        },
        {
            'Name': 'SecondaryDNSServer2Status',
            'LocalizedName': 'Secondary DNS 2 Status',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 100,
            'Description': 'Secondary DNS Server (Ethernet Adapter 2)',
            'IsUdf': false
        },
        {
            'Name': 'SecureViolationStatus',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': -1,
            'Description': 'The current value of the Secure Violation Status for this Edge G2 Controller.',
            'IsUdf': false
        },
        {
            'Name': 'SNMPEnabled',
            'LocalizedName': 'SNMP Enabled',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'SNMP Enabled',
            'IsUdf': false
        },
        {
            'Name': 'SubNetMask1Status',
            'LocalizedName': 'Subnet Mask 1 Status',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 100,
            'Description': 'Subnet mask',
            'IsUdf': false
        },
        {
            'Name': 'SubNetMask2Status',
            'LocalizedName': 'Subnet Mask 2 Status',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 100,
            'Description': 'Subnet mask',
            'IsUdf': false
        },
        {
            'Name': 'SuperCapChargeStatus',
            'LocalizedName': 'Super Cap Charge Status',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': true,
            'Type': 'SoftwareHouse.NextGen.Common.SecurityObjectDefinitions.SuperCapChargeStatus',
            'IsEnum': true,
            'Description': 'The current value of the Super Cap Charge Status for this Edge G2 Controller.',
            'IsUdf': false
        },
        {
            'Name': 'SupportsEcc',
            'LocalizedName': 'Supports ECC',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': false,
            'Type': 'String',
            'IsEnum': false,
            'Description': 'Whether this iSTAR Controller supports ECC or not',
            'LinkedProperties': [
                'FirmwareVersionStatus'
            ],
            'IsUdf': false
        },
        {
            'Name': 'TCPPort',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'MinValue': 0.0,
            'MaxValue': 2147483647.0,
            'Description': 'The TCP port number.',
            'IsUdf': false
        },
        {
            'Name': 'Template',
            'LocalizedName': 'Template',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'Whether this iSTAR controller can be used as a template or not.',
            'IsUdf': false
        },
        {
            'Name': 'TimeZone',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'MinValue': -2147483648.0,
            'MaxValue': 2147483647.0,
            'Description': 'Select the time zone for this iSTAR controller.',
            'IsUdf': false
        },
        {
            'Name': 'TimeZoneKey',
            'LocalizedName': 'Time Zone',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': false,
            'Type': 'ObjectKey',
            'IsEnum': false,
            'Description': 'The name of the time zone associated with this iSTAR controller.',
            'LinkedProperties': [
                'TimeZone'
            ],
            'LookupData': {
                'IsQueryable': true,
                'PersistentTypeProperty': '',
                'PersistentIdProperty': 'TimeZone',
                'TargetName': 'Name',
                'TargetObjectID': 'ObjectID',
                'ValidLookupTypes': [
                    'SoftwareHouse.CrossFire.Common.Objects.TimeZone'
                ]
            },
            'IsUdf': false
        },
        {
            'Name': 'Token',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 100,
            'Description': '*** iStarControllerTokenToolTipText ***',
            'IsUdf': false
        },
        {
            'Name': 'Ultra16Reader',
            'LocalizedName': 'Ultra LT 16 Reader Configured',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'Configured for  8 or 16 readers maximum',
            'IsUdf': false
        },
        {
            'Name': 'UltraMode',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'Whether this Ultra G2 is in Ultra Mode or not',
            'IsUdf': false
        },
        {
            'Name': 'UltraReaderStatus',
            'LocalizedName': 'Ultra LT Reader Status',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': true,
            'Type': 'SoftwareHouse.NextGen.Common.SecurityObjectDefinitions.UltraReaderMaxStatus',
            'IsEnum': true,
            'Description': 'Actual Ultra LT  Hardware Version ',
            'IsUdf': false
        },
        {
            'Name': 'UseDHCP',
            'LocalizedName': 'Use DHCP',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'Use DHCP for Onboard NIC IP Address 1',
            'IsUdf': false
        },
        {
            'Name': 'UseDHCP2',
            'LocalizedName': 'Use DHCP2',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'Use DHCP for Onboard NIC IP Address 2',
            'IsUdf': false
        },
        {
            'Name': 'WebCertificateCreatedTime',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'DateTime',
            'IsEnum': false,
            'Description': 'The timestamp that the Web certificate was created.',
            'DateTimeKind': 'Local',
            'DynamicViewColumnType': 'DateTime',
            'IsUdf': false
        },
        {
            'Name': 'WebCertificateExpiringTime',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'DateTime',
            'IsEnum': false,
            'Description': 'The timestamp that the Web certificate will expire.',
            'DateTimeKind': 'Local',
            'DynamicViewColumnType': 'DateTime',
            'IsUdf': false
        },
        {
            'Name': 'WebDiagnosticsEnabled',
            'LocalizedName': 'Web Diagnostics Enabled',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'Controller Web Diagnostics Enabled',
            'IsUdf': false
        }
    ]
};

export { typeName, schema };