/* eslint-disable @typescript-eslint/no-loss-of-precision */
const typeName = 'SoftwareHouse.NextGen.Common.SecurityObjects.Output';
const schema = {
    'FullClassName': 'SoftwareHouse.NextGen.Common.SecurityObjects.Output',
    'LocalizedName': 'Output',
    'IsUserSelectable': true,
    'LocalityType': 'LocalOnly',
    'Description': 'This class is used to specify an Output in the system.',
    'IsGroupable': true,
    'PropertyList': [
        {
            'Name': 'Name',
            'LocalizedName': 'Name',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 200,
            'Description': 'The name of this output.',
            'IsUdf': false
        },
        {
            'Name': 'Description',
            'LocalizedName': 'Description',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 500,
            'Description': 'The description of this output.',
            'IsUdf': false
        },
        {
            'Name': 'GUID',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Guid',
            'IsEnum': false,
            'Description': 'GUID.',
            'IsUdf': false
        },
        {
            'Name': 'ActiveMode',
            'LocalizedName': 'Active Mode',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'SoftwareHouse.NextGen.Common.SecurityObjectDefinitions.OutputModes',
            'IsEnum': true,
            'Description': 'The current value for Active Mode for this output.',
            'IsUdf': false
        },
        {
            'Name': 'ActiveReasonStatus',
            'LocalizedName': 'Active Reason Status',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'SoftwareHouse.NextGen.Common.SecurityObjectDefinitions.OutputActiveReasonStatus',
            'IsEnum': true,
            'Description': 'The current value for Active Reason Status for this output.',
            'IsUdf': false
        },
        {
            'Name': 'ActiveStateStatus',
            'LocalizedName': 'Active State Status ',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'SoftwareHouse.NextGen.Common.SecurityObjectDefinitions.OutputActiveStateStatus',
            'IsEnum': true,
            'Description': 'The current value for Active State Status for this output.',
            'IsUdf': false
        },
        {
            'Name': 'ActiveStatus',
            'LocalizedName': 'Active Status',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'SoftwareHouse.NextGen.Common.SecurityObjectDefinitions.OutputStateStatus',
            'IsEnum': true,
            'Description': 'Whether or not this output is currently active.',
            'IsUdf': false
        },
        {
            'Name': 'Annunciate',
            'LocalizedName': 'Annunciate',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'Check whether or not to send state changes to Journal for this output.',
            'IsUdf': false
        },
        {
            'Name': 'BoardClassType',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Type',
            'IsEnum': false,
            'Description': 'The class type of the current board for this output.',
            'IsUdf': false
        },
        {
            'Name': 'BoardID',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'MinValue': 1.0,
            'MaxValue': 2147483647.0,
            'Description': 'Board ID.',
            'IsUdf': false
        },
        {
            'Name': 'BoardObjectKey',
            'LocalizedName': 'Board',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': false,
            'Type': 'ObjectKey',
            'IsEnum': false,
            'Description': 'The parent board of this output.',
            'LinkedProperties': [
                'BoardID',
                'BoardClassType'
            ],
            'LookupData': {
                'IsQueryable': true,
                'PersistentTypeProperty': 'BoardClassType',
                'PersistentIdProperty': 'BoardID',
                'TargetName': 'Name',
                'TargetObjectID': 'ObjectID',
                'ValidLookupTypes': [
                    'SoftwareHouse.NextGen.Common.SecurityObjects.Reader',
                    'SoftwareHouse.NextGen.Common.SecurityObjects.iStarPIM485Reader',
                    'SoftwareHouse.NextGen.Common.SecurityObjects.iStarS300Reader',
                    'SoftwareHouse.NextGen.Common.SecurityObjects.ISCReader',
                    'SoftwareHouse.NextGen.Common.SecurityObjects.iStarReader',
                    'SoftwareHouse.NextGen.Common.SecurityObjects.iSTARAperioReader',
                    'SoftwareHouse.NextGen.Common.SecurityObjects.CC8xReader',
                    'SoftwareHouse.NextGen.Common.SecurityObjects.ApcReader',
                    'SoftwareHouse.NextGen.Common.SecurityObjects.iStarBoard',
                    'SoftwareHouse.NextGen.Common.SecurityObjects.iStarEdgeG2GCBoard',
                    'SoftwareHouse.NextGen.Common.SecurityObjects.iStarOutputBoard',
                    'SoftwareHouse.NextGen.Common.SecurityObjects.iStarACMBoard',
                    'SoftwareHouse.NextGen.Common.SecurityObjects.iStarAperioHubBoard',
                    'SoftwareHouse.NextGen.Common.SecurityObjects.iStarInputBoard',
                    'SoftwareHouse.NextGen.Common.SecurityObjects.iStarS300Board',
                    'SoftwareHouse.NextGen.Common.SecurityObjects.iStarPIM485Board',
                    'SoftwareHouse.NextGen.Common.SecurityObjects.iStarUltraACMBoard',
                    'SoftwareHouse.NextGen.Common.SecurityObjects.iStarUltraIPACMBoard',
                    'SoftwareHouse.NextGen.Common.SecurityObjects.iStarVirtualUltraACMBoard',
                    'SoftwareHouse.NextGen.Common.SecurityObjects.iStarGCBoard',
                    'SoftwareHouse.NextGen.Common.SecurityObjects.iStarComBoard',
                    'SoftwareHouse.NextGen.Common.SecurityObjects.ApcBoard',
                    'SoftwareHouse.NextGen.Common.SecurityObjects.ApcMainBoard',
                    'SoftwareHouse.NextGen.Common.SecurityObjects.ApcR48OutputBoard',
                    'SoftwareHouse.NextGen.Common.SecurityObjects.ApcStarCouplerStar',
                    'SoftwareHouse.NextGen.Common.SecurityObjects.ApcI8InputBoard',
                    'SoftwareHouse.NextGen.Common.SecurityObjects.ApcStarCouplerWPSC',
                    'SoftwareHouse.NextGen.Common.SecurityObjects.ApcI32InputBoard',
                    'SoftwareHouse.NextGen.Common.SecurityObjects.ApcAddOnBoard',
                    'SoftwareHouse.NextGen.Common.SecurityObjects.ApcR8OutputBoard',
                    'SoftwareHouse.NextGen.Common.SecurityObjects.ApcStarCouplerMiniStar',
                    'SoftwareHouse.NextGen.Common.SecurityObjects.BaseControllerBoard',
                    'SoftwareHouse.NextGen.Common.SecurityObjects.BaseControllerMainBoard'
                ]
            },
            'IsUdf': false
        },
        {
            'Name': 'ClassType',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': true,
            'Type': 'Type',
            'IsEnum': false,
            'IsUdf': false
        },
        {
            'Name': 'ControllerClassType',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Type',
            'IsEnum': false,
            'Description': 'The current Controller Class Type for this output.',
            'IsUdf': false
        },
        {
            'Name': 'ControllerID',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'MinValue': 1.0,
            'MaxValue': 2147483647.0,
            'Description': 'Controller ID.',
            'IsUdf': false
        },
        {
            'Name': 'ControllerObjectKey',
            'LocalizedName': 'Controller',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': false,
            'Type': 'ObjectKey',
            'IsEnum': false,
            'Description': 'The controller associated with this output.',
            'LinkedProperties': [
                'ControllerID',
                'ControllerClassType'
            ],
            'LookupData': {
                'IsQueryable': true,
                'PersistentTypeProperty': 'ControllerClassType',
                'PersistentIdProperty': 'ControllerID',
                'TargetName': 'Name',
                'TargetObjectID': 'ObjectID',
                'ValidLookupTypes': [
                    'SoftwareHouse.NextGen.Common.SecurityObjects.ApcController',
                    'SoftwareHouse.NextGen.Common.SecurityObjects.iStarController',
                    'SoftwareHouse.NextGen.Common.SecurityObjects.iStarClassicController',
                    'SoftwareHouse.NextGen.Common.SecurityObjects.iStarProController',
                    'SoftwareHouse.NextGen.Common.SecurityObjects.iStareXController',
                    'SoftwareHouse.NextGen.Common.SecurityObjects.iStarVideoController',
                    'SoftwareHouse.NextGen.Common.SecurityObjects.iStarEdgeController',
                    'SoftwareHouse.NextGen.Common.SecurityObjects.iStarUltraLiteController',
                    'SoftwareHouse.NextGen.Common.SecurityObjects.iStarUltraController',
                    'SoftwareHouse.NextGen.Common.SecurityObjects.iStarUltraG2Controller',
                    'SoftwareHouse.NextGen.Common.SecurityObjects.iStarEdgeG2Controller',
                    'SoftwareHouse.NextGen.Common.SecurityObjects.BaseController'
                ]
            },
            'IsUdf': false
        },
        {
            'Name': 'Enabled',
            'LocalizedName': 'Enabled',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'Check whether or not this output is enabled.',
            'IsUdf': false
        },
        {
            'Name': 'GeographicLocation',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': -1,
            'Description': 'Location',
            'IsUdf': false
        },
        {
            'Name': 'GISLocation',
            'LocalizedName': 'GIS Location',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': false,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'Location',
            'LinkedProperties': [
                'GeographicLocation'
            ],
            'IsUdf': false
        },
        {
            'Name': 'LastModifiedByID',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'MinValue': 1.0,
            'MaxValue': 2147483647.0,
            'Description': 'The ID of the operator who last modified this output.',
            'IsUdf': false
        },
        {
            'Name': 'LastModifiedTime',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'DateTime',
            'IsEnum': false,
            'Description': 'The timestamp of the last modification of this output.',
            'DateTimeKind': 'Local',
            'DynamicViewColumnType': 'DateTime',
            'IsUdf': false
        },
        {
            'Name': 'LocationMetaTagFullName',
            'LocalizedName': 'Location Tag Path',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': false,
            'Type': 'String',
            'IsEnum': false,
            'Description': 'Represents the full path name of the objects location tag.',
            'LinkedProperties': null,
            'IsUdf': false
        },
        {
            'Name': 'MaintenanceMode',
            'LocalizedName': 'Maintenance Mode',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': ' The current Maintenance Mode value for this output.',
            'IsUdf': false
        },
        {
            'Name': 'ModeStatus',
            'LocalizedName': 'Mode Status',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'SoftwareHouse.NextGen.Common.SecurityObjectDefinitions.OutputModes',
            'IsEnum': true,
            'Description': 'The status of the output mode.',
            'IsUdf': false
        },
        {
            'Name': 'Momentary',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'Default tooltip text for property Momentary.',
            'IsUdf': false
        },
        {
            'Name': 'MomentaryTime',
            'LocalizedName': 'Pulse Duration',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int64',
            'IsEnum': false,
            'Description': 'The amount of time that output will activate on a momentary action.',
            'IsUdf': false
        },
        {
            'Name': 'MonitorState',
            'LocalizedName': 'Monitor State',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': false,
            'Type': 'SoftwareHouse.NextGen.Common.SecurityObjectDefinitions.OutputMonitorState',
            'IsEnum': true,
            'Description': 'The current monitor state of this output.',
            'LinkedProperties': [
                'Enabled',
                'ActiveStatus'
            ],
            'IsUdf': false
        },
        {
            'Name': 'NormallyEnergized',
            'LocalizedName': 'Normally Energized',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'Check whether or not this output is normally energized.',
            'IsUdf': false
        },
        {
            'Name': 'ObjectID',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'MinValue': -2147483648.0,
            'MaxValue': 2147483647.0,
            'Description': 'Default tooltip text for property ObjectID.',
            'IsUdf': false
        },
        {
            'Name': 'ObjectKey',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': false,
            'Type': 'ObjectKey',
            'IsEnum': false,
            'IsUdf': false
        },
        {
            'Name': 'OutputType',
            'LocalizedName': 'Output Type',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'SoftwareHouse.NextGen.Common.SecurityObjectDefinitions.OutputTypes',
            'IsEnum': true,
            'Description': 'The type of this output.',
            'IsUdf': false
        },
        {
            'Name': 'OwnerClassType',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Type',
            'IsEnum': false,
            'Description': 'Owner Class Type.',
            'IsUdf': false
        },
        {
            'Name': 'OwnerID',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'MinValue': 1.0,
            'MaxValue': 2147483647.0,
            'Description': 'Owner ID.',
            'IsUdf': false
        },
        {
            'Name': 'OwnerObjectKey',
            'LocalizedName': 'Owner',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': false,
            'Type': 'ObjectKey',
            'IsEnum': false,
            'Description': 'The owner of this output.',
            'LinkedProperties': [
                'OwnerID',
                'OwnerClassType'
            ],
            'LookupData': {
                'IsQueryable': true,
                'PersistentTypeProperty': 'OwnerClassType',
                'PersistentIdProperty': 'OwnerID',
                'TargetName': 'Name',
                'TargetObjectID': 'ObjectID',
                'ValidLookupTypes': [
                    'SoftwareHouse.NextGen.Common.SecurityObjects.Door',
                    'SoftwareHouse.NextGen.Common.SecurityObjects.Button'
                ]
            },
            'IsUdf': false
        },
        {
            'Name': 'ParentClassType',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Type',
            'IsEnum': false,
            'Description': 'Parent Class Type.',
            'IsUdf': false
        },
        {
            'Name': 'ParentID',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'MinValue': 1.0,
            'MaxValue': 2147483647.0,
            'Description': 'Parent ID.',
            'IsUdf': false
        },
        {
            'Name': 'PartitionID',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'MinValue': 1.0,
            'MaxValue': 2147483647.0,
            'Description': 'Partition ID.',
            'IsUdf': false
        },
        {
            'Name': 'PartitionKey',
            'LocalizedName': 'Partition Name',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': false,
            'Type': 'ObjectKey',
            'IsEnum': false,
            'Description': 'Partition of object',
            'LinkedProperties': [
                'PartitionID'
            ],
            'LookupData': {
                'IsQueryable': true,
                'PersistentTypeProperty': '',
                'PersistentIdProperty': 'PartitionID',
                'TargetName': 'Name',
                'TargetObjectID': 'ObjectID',
                'ValidLookupTypes': [
                    'SoftwareHouse.CrossFire.Common.Objects.Partition'
                ]
            },
            'IsUdf': false
        },
        {
            'Name': 'Protected',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'Protected.',
            'IsUdf': false
        },
        {
            'Name': 'SendToJournal',
            'LocalizedName': 'Send to Journal',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'Sendstate change to journal.',
            'IsUdf': false
        },
        {
            'Name': 'SendToMonitorStation',
            'LocalizedName': 'Send to Monitoring Station',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'Send state change to monitor station.',
            'IsUdf': false
        },
        {
            'Name': 'SlotIndex',
            'LocalizedName': 'Slot Index',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'MinValue': -2.0,
            'MaxValue': 2147483647.0,
            'Description': 'The physical connection point of this output.',
            'IsUdf': false
        },
        {
            'Name': 'Template',
            'LocalizedName': 'Template',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'Template.',
            'IsUdf': false
        },
        {
            'Name': 'TimeZoneID',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'MinValue': -2147483648.0,
            'MaxValue': 2147483647.0,
            'Description': '*** OutputTimeZoneToolTipText ***',
            'IsUdf': false
        },
        {
            'Name': 'TimeZoneKey',
            'LocalizedName': 'Time Zone',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': false,
            'Type': 'ObjectKey',
            'IsEnum': false,
            'Description': 'Time Zone for this output.',
            'LinkedProperties': [
                'TimeZoneID'
            ],
            'LookupData': {
                'IsQueryable': true,
                'PersistentTypeProperty': '',
                'PersistentIdProperty': 'TimeZoneID',
                'TargetName': 'Name',
                'TargetObjectID': 'ObjectID',
                'ValidLookupTypes': [
                    'SoftwareHouse.CrossFire.Common.Objects.TimeZone'
                ]
            },
            'IsUdf': false
        }
    ]
};

export { typeName, schema };