/* eslint-disable @typescript-eslint/no-loss-of-precision */
const typeName = 'SoftwareHouse.NextGen.Common.SecurityObjects.Personnel';
const schema = {
    'FullClassName': 'SoftwareHouse.NextGen.Common.SecurityObjects.Personnel',
    'LocalizedName': 'Personnel',
    'IsUserSelectable': true,
    'LocalityType': 'OptionallyGlobal',
    'Description': 'This class is used to specify a Personnel Record in the system.',
    'IsGroupable': true,
    'PropertyList': [
        {
            'Name': 'Name',
            'LocalizedName': 'Name',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 200,
            'Description': 'The name of this person.',
            'IsUdf': false
        },
        {
            'Name': 'Description',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 500,
            'Description': 'The description of this person.',
            'IsUdf': false
        },
        {
            'Name': 'GUID',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Guid',
            'IsEnum': false,
            'Description': 'The GUID of this personnel record.',
            'IsUdf': false
        },
        {
            'Name': 'ADAPINExempt',
            'LocalizedName': 'PIN Exempt (ADA)',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'Whether this person is exempt from entering PIN due to ADA or not.',
            'IsUdf': false
        },
        {
            'Name': 'AllowVisitReception',
            'LocalizedName': 'Allow Visit Reception',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'Whether this person is allowed to manage visit reception or not',
            'IsUdf': false
        },
        {
            'Name': 'AlternateShunt',
            'LocalizedName': 'Alternate Shunt (ADA)',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'Select this box if this person is someone with Americans with Disabilities Act (ADA) status or whenever you need to use the door with Alternate Shunt capabilities. ',
            'IsUdf': false
        },
        {
            'Name': 'APBEvent',
            'LocalizedName': 'Antipassback Event',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'Whether an anti-passback violation activates an event.',
            'IsUdf': false
        },
        {
            'Name': 'APBExempt',
            'LocalizedName': 'Antipassback Exempt',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'Whether the person is exempt from anti-passback restrictions.',
            'IsUdf': false
        },
        {
            'Name': 'AreaAccessTime',
            'LocalizedName': 'Area Access Time',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'DateTime',
            'IsEnum': false,
            'Description': 'Time of last valid entry to an area.',
            'DateTimeKind': 'Local',
            'DynamicViewColumnType': 'UTCDateTime',
            'IsUdf': false
        },
        {
            'Name': 'AreaID',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'MinValue': 0.0,
            'MaxValue': 2147483647.0,
            'Description': 'Area ID.',
            'IsUdf': false
        },
        {
            'Name': 'AreaKey',
            'LocalizedName': 'Area',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': false,
            'Type': 'ObjectKey',
            'IsEnum': false,
            'Description': 'Last valid area occupied by this user ',
            'LinkedProperties': [
                'AreaID'
            ],
            'LookupData': {
                'IsQueryable': true,
                'PersistentTypeProperty': '',
                'PersistentIdProperty': 'AreaID',
                'TargetName': 'Name',
                'TargetObjectID': 'ObjectID',
                'ValidLookupTypes': [
                    'SoftwareHouse.NextGen.Common.SecurityObjects.Area'
                ]
            },
            'IsUdf': false
        },
        {
            'Name': 'CanApproveRequests',
            'LocalizedName': 'Can Approve Requests',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'Whether this person can approve requests or not.',
            'IsUdf': false
        },
        {
            'Name': 'CanHost',
            'LocalizedName': 'Can Host Visit',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'Specifies whether this person can host a visit',
            'IsUdf': false
        },
        {
            'Name': 'CanPerformGuardTour',
            'LocalizedName': 'Can Perform Guard Tour',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'Person can participate in Guard Tours',
            'IsUdf': false
        },
        {
            'Name': 'CanSubmitRequests',
            'LocalizedName': 'Can Submit Requests',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'Whether this person can submit requests or not',
            'IsUdf': false
        },
        {
            'Name': 'CarpoolAreaID',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'MinValue': 0.0,
            'MaxValue': 2147483647.0,
            'Description': 'Object ID of last valid Carpool Area used.',
            'IsUdf': false
        },
        {
            'Name': 'CarpoolAreaKey',
            'LocalizedName': 'Carpool Area',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': false,
            'Type': 'ObjectKey',
            'IsEnum': false,
            'Description': 'Last valid Carpool Area used.',
            'LinkedProperties': [
                'CarpoolAreaID'
            ],
            'LookupData': {
                'IsQueryable': true,
                'PersistentTypeProperty': '',
                'PersistentIdProperty': 'CarpoolAreaID',
                'TargetName': 'Name',
                'TargetObjectID': 'ObjectID',
                'ValidLookupTypes': [
                    'SoftwareHouse.NextGen.Common.SecurityObjects.Area'
                ]
            },
            'IsUdf': false
        },
        {
            'Name': 'CarpoolDriverStatus',
            'LocalizedName': 'Carpool Driver',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'Is this person currently the driver of their carpool.',
            'IsUdf': false
        },
        {
            'Name': 'CheckedInVisit',
            'LocalizedName': 'Checked In for a Visit',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': false,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'Indicates whether this person is checked in to a visit',
            'LinkedProperties': [
                'CheckedInVisitID'
            ],
            'IsUdf': false
        },
        {
            'Name': 'CheckedInVisitID',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'Description': 'The name of the Visit for which this visitor is checked in, if any.',
            'IsUdf': false
        },
        {
            'Name': 'CheckedInVisitKey',
            'LocalizedName': 'Visit Name',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': false,
            'Type': 'ObjectKey',
            'IsEnum': false,
            'Description': 'The name of the Visit for which this visitor is checked in, if any.',
            'LinkedProperties': [
                'CheckedInVisitID'
            ],
            'LookupData': {
                'IsQueryable': true,
                'PersistentTypeProperty': '',
                'PersistentIdProperty': 'CheckedInVisitID',
                'TargetName': 'Name',
                'TargetObjectID': 'ObjectID',
                'ValidLookupTypes': [
                    'SoftwareHouse.NextGen.Common.SecurityObjects.Visit'
                ]
            },
            'IsUdf': false
        },
        {
            'Name': 'ClassType',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': true,
            'Type': 'Type',
            'IsEnum': false,
            'IsUdf': false
        },
        {
            'Name': 'ClearanceFilter',
            'LocalizedName': 'Clearance Filter',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'SoftwareHouse.NextGen.Common.SecurityObjectDefinitions.ClearanceFilterTypes',
            'IsEnum': true,
            'Description': 'Default value of Clearance Filter to be used if the Temporary Clearance Filter is not defined',
            'IsUdf': false
        },
        {
            'Name': 'CloudRegistrationCompleted',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'DateTime',
            'IsEnum': false,
            'Description': 'The date the cloud registration process completed.',
            'IsUdf': false
        },
        {
            'Name': 'CloudRegistrationInitiated',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'DateTime',
            'IsEnum': false,
            'Description': 'The date this personnel was sent to initiate the cloud registration process.',
            'IsUdf': false
        },
        {
            'Name': 'Date1',
            'LocalizedName': 'Date1',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Date',
            'IsEnum': false,
            'Description': 'Customer Field: Date1',
            'DynamicViewColumnType': 'Date',
            'IsUdf': false
        },
        {
            'Name': 'Date2',
            'LocalizedName': 'Date2',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Date',
            'IsEnum': false,
            'Description': 'Customer Field:  Date2',
            'DynamicViewColumnType': 'Date',
            'IsUdf': false
        },
        {
            'Name': 'Date3',
            'LocalizedName': 'Date3',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Date',
            'IsEnum': false,
            'Description': 'Customer Field:  Date3',
            'DynamicViewColumnType': 'Date',
            'IsUdf': false
        },
        {
            'Name': 'Date4',
            'LocalizedName': 'Date4',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Date',
            'IsEnum': false,
            'Description': 'Customer Field:  Date4',
            'DynamicViewColumnType': 'Date',
            'IsUdf': false
        },
        {
            'Name': 'Disabled',
            'LocalizedName': 'Disabled',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'Disables the personnel record and denies the person access.',
            'IsUdf': false
        },
        {
            'Name': 'EmailAddress',
            'LocalizedName': 'Email Address',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 100,
            'Description': 'Enter email address ( Changing this invalidates the web password )',
            'IsUdf': false
        },
        {
            'Name': 'EnableForBLE',
            'LocalizedName': 'BLE Enabled',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'Check to enable this person to use BLE Door Readers',
            'IsUdf': false
        },
        {
            'Name': 'EnableMobileAlert',
            'LocalizedName': 'Mobile Alert Enabled',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'Check to enable this person to use Mobile Alert',
            'IsUdf': false
        },
        {
            'Name': 'EnableMobileKey',
            'LocalizedName': 'Mobile Key Enabled',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'Check to enable this person to use Mobile Key',
            'IsUdf': false
        },
        {
            'Name': 'EncodedPassword',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': true,
            'Type': 'Binary',
            'IsEnum': false,
            'IsUdf': false
        },
        {
            'Name': 'EscortOption',
            'LocalizedName': 'Escort Option',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'SoftwareHouse.NextGen.Common.SecurityObjectDefinitions.EscortOptionType',
            'IsEnum': true,
            'Description': 'Select an option if person is a Visitor, Escorted Visitor, or Escort.',
            'IsUdf': false
        },
        {
            'Name': 'FirstName',
            'LocalizedName': 'First Name',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 63,
            'Description': 'Enter First Name',
            'IsUdf': false
        },
        {
            'Name': 'ImportedDecodedPIN',
            'LocalizedName': 'PIN',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': false,
            'Type': 'Int32',
            'IsEnum': false,
            'Description': 'The Decoded, importable PIN for this personnel record.',
            'LinkedProperties': [
                'PIN'
            ],
            'IsUdf': false
        },
        {
            'Name': 'InactivityExempt',
            'LocalizedName': 'Inactivity Exempt',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'Inactivity Exempt',
            'IsUdf': false
        },
        {
            'Name': 'Int1',
            'LocalizedName': 'Int1',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int64',
            'IsEnum': false,
            'MinValue': 0.0,
            'MaxValue': 9223372036854775807.0,
            'Description': 'Customer Field: Enter a number between 0 and 9223372036854775807',
            'IsUdf': false
        },
        {
            'Name': 'Int2',
            'LocalizedName': 'Int2',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int64',
            'IsEnum': false,
            'MinValue': 0.0,
            'MaxValue': 9223372036854775807.0,
            'Description': 'Customer Field: Enter a number between 0 and 9223372036854775807',
            'IsUdf': false
        },
        {
            'Name': 'Int3',
            'LocalizedName': 'Int3',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int64',
            'IsEnum': false,
            'MinValue': 0.0,
            'MaxValue': 9223372036854775807.0,
            'Description': 'Customer Field: Enter a number between 0 and 9223372036854775807',
            'IsUdf': false
        },
        {
            'Name': 'Int4',
            'LocalizedName': 'Int4',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int64',
            'IsEnum': false,
            'MinValue': 0.0,
            'MaxValue': 9223372036854775807.0,
            'Description': 'Customer Field: Enter a number between 0 and 9223372036854775807',
            'IsUdf': false
        },
        {
            'Name': 'Int5',
            'LocalizedName': 'Int5',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int64',
            'IsEnum': false,
            'MinValue': 0.0,
            'MaxValue': 9223372036854775807.0,
            'Description': 'Customer Field: Enter a number between 0 and 9223372036854775807',
            'IsUdf': false
        },
        {
            'Name': 'Int6',
            'LocalizedName': 'Int6',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int64',
            'IsEnum': false,
            'MinValue': 0.0,
            'MaxValue': 9223372036854775807.0,
            'Description': 'Customer Field: Enter a unique number between 0 and 9223372036854775807',
            'IsUdf': false
        },
        {
            'Name': 'Int7',
            'LocalizedName': 'Int7',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int64',
            'IsEnum': false,
            'MinValue': 0.0,
            'MaxValue': 9223372036854775807.0,
            'Description': 'Customer Field: Enter a number between 0 and 9223372036854775807',
            'IsUdf': false
        },
        {
            'Name': 'Int8',
            'LocalizedName': 'Int8',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int64',
            'IsEnum': false,
            'MinValue': 0.0,
            'MaxValue': 9223372036854775807.0,
            'Description': 'Customer Field: Enter a number between 0 and 9223372036854775807',
            'IsUdf': false
        },
        {
            'Name': 'Int9',
            'LocalizedName': 'Int9',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int64',
            'IsEnum': false,
            'MinValue': 0.0,
            'MaxValue': 9223372036854775807.0,
            'Description': 'Customer Field: Enter a number between 0 and 9223372036854775807',
            'IsUdf': false
        },
        {
            'Name': 'IntrusionZoneAdmin',
            'LocalizedName': 'Intrusion Zone Administrator',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'Whether this person is an intrusion zone administrator or not.',
            'IsUdf': false
        },
        {
            'Name': 'KeypadCommandAdmin',
            'LocalizedName': 'Keypad Command Administrator',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'Whether this person is a keypad command administrator or not.',
            'IsUdf': false
        },
        {
            'Name': 'LastModAppServerID',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'MinValue': 0.0,
            'MaxValue': 9223372036854775807.0,
            'Description': 'Enter a number between 0 and 9223372036854775807',
            'IsUdf': false
        },
        {
            'Name': 'LastModifiedByID',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'MinValue': 1.0,
            'MaxValue': 2147483647.0,
            'Description': 'ID of Operator or Personnel that modified the record last.',
            'IsUdf': false
        },
        {
            'Name': 'LastModifiedByOperator',
            'LocalizedName': 'Last Modified by Operator',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': false,
            'Type': 'ObjectKey',
            'IsEnum': false,
            'LinkedProperties': [
                'LastModifiedByID'
            ],
            'LookupData': {
                'IsQueryable': true,
                'PersistentTypeProperty': 'LastModifiedByTypeName',
                'PersistentIdProperty': 'PositiveLastModifiedByID',
                'TargetName': 'Name',
                'TargetObjectID': 'ObjectID',
                'ValidLookupTypes': [
                    'SoftwareHouse.CrossFire.Common.Objects.Operator',
                    'SoftwareHouse.NextGen.Common.SecurityObjects.Personnel'
                ]
            },
            'IsUdf': false
        },
        {
            'Name': 'LastModifiedByType',
            'LocalizedName': 'Last Modified by Type',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': false,
            'Type': 'Type',
            'IsEnum': false,
            'LinkedProperties': [
                'LastModifiedByID'
            ],
            'LookupData': {
                'IsQueryable': true,
                'PersistentTypeProperty': 'LastModifiedByTypeName',
                'PersistentIdProperty': 'LastModifiedByTypeName',
                'TargetName': '',
                'TargetObjectID': '',
                'ValidLookupTypes': []
            },
            'IsUdf': false
        },
        {
            'Name': 'LastModifiedTime',
            'LocalizedName': 'Last Modified Time',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'DateTime',
            'IsEnum': false,
            'Description': 'The time of the last modification of this personnel record.',
            'DateTimeKind': 'Local',
            'DynamicViewColumnType': 'UTCDateTime',
            'IsUdf': false
        },
        {
            'Name': 'LastName',
            'LocalizedName': 'Last Name',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 63,
            'Description': 'Enter Last Name',
            'IsUdf': false
        },
        {
            'Name': 'LastVisitTime',
            'LocalizedName': 'Last Visit Time (UTC)',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'DateTime',
            'IsEnum': false,
            'Description': 'Specifies the last time this person visited',
            'DateTimeKind': 'Unspecified',
            'DynamicViewColumnType': 'UTCDateTime',
            'IsUdf': false
        },
        {
            'Name': 'LastVisitTimeLocal',
            'LocalizedName': 'Last Visit Time (Local)',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': false,
            'Type': 'DateTime',
            'IsEnum': false,
            'Description': 'Specifies the last time this person visited',
            'DateTimeKind': 'Local',
            'DynamicViewColumnType': 'DateTime',
            'LinkedProperties': [
                'LastVisitTime'
            ],
            'IsUdf': false
        },
        {
            'Name': 'LocationMetaTagFullName',
            'LocalizedName': 'Location Tag Path',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': false,
            'Type': 'String',
            'IsEnum': false,
            'Description': 'Represents the full path name of the objects location tag.',
            'LinkedProperties': null,
            'IsUdf': false
        },
        {
            'Name': 'Logical1',
            'LocalizedName': 'Logical1',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'Customer Field: Logical 1',
            'IsUdf': false
        },
        {
            'Name': 'Logical2',
            'LocalizedName': 'Logical2',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'Customer Field: Logical 2',
            'IsUdf': false
        },
        {
            'Name': 'Logical3',
            'LocalizedName': 'Logical3',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'Customer Field: Logical 3',
            'IsUdf': false
        },
        {
            'Name': 'Logical4',
            'LocalizedName': 'Logical4',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'Customer Field: Logical 4',
            'IsUdf': false
        },
        {
            'Name': 'LostCredentials',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'MinValue': 0.0,
            'MaxValue': 9223372036854775807.0,
            'Description': 'The number of credentials lost by this person over time',
            'IsUdf': false
        },
        {
            'Name': 'ManagerEmail',
            'LocalizedName': 'Manager\'s Email',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 100,
            'Description': 'Manager\'s Email',
            'IsUdf': false
        },
        {
            'Name': 'MiddleName',
            'LocalizedName': 'Middle Name',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 63,
            'Description': 'Enter Middle Name',
            'IsUdf': false
        },
        {
            'Name': 'MobileDoor1',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': false,
            'Type': 'ObjectKey',
            'IsEnum': false,
            'IsUdf': false
        },
        {
            'Name': 'MobileDoor2',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': false,
            'Type': 'ObjectKey',
            'IsEnum': false,
            'IsUdf': false
        },
        {
            'Name': 'MobileEnrollmentStatus',
            'LocalizedName': 'Mobile Enrollment Status',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': false,
            'Type': 'String',
            'IsEnum': false,
            'Description': 'Shows the status of the cloud enrollment process',
            'LinkedProperties': [
                'CloudRegistrationInitiated',
                'CloudRegistrationCompleted'
            ],
            'IsUdf': false
        },
        {
            'Name': 'MobileEnrollmentStatusWithDate',
            'LocalizedName': 'Mobile Enrollment Status (incl. Date)',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': false,
            'Type': 'String',
            'IsEnum': false,
            'Description': 'Shows the status of the mobile enrollment process, including date information',
            'LinkedProperties': [
                'CloudRegistrationInitiated',
                'CloudRegistrationCompleted'
            ],
            'IsUdf': false
        },
        {
            'Name': 'MobileKeyDoor1',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': false,
            'Type': 'ObjectKey',
            'IsEnum': false,
            'Description': 'Select the first door this person can open with Mobile Key',
            'LinkedProperties': [
                'MobileDoor1'
            ],
            'IsUdf': false
        },
        {
            'Name': 'MobileKeyDoor2',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': false,
            'Type': 'ObjectKey',
            'IsEnum': false,
            'Description': 'Select the second door this person can open with Mobile Key',
            'LinkedProperties': [
                'MobileDoor2'
            ],
            'IsUdf': false
        },
        {
            'Name': 'Noticed',
            'LocalizedName': 'Noticed',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'Noticed Displays the tag Noticed in admit or reject access message. Also triggers the noticed events you defined when configuring doors.',
            'IsUdf': false
        },
        {
            'Name': 'ObjectID',
            'LocalizedName': 'Object ID',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'MinValue': 0.0,
            'MaxValue': 2147483647.0,
            'Description': 'System assigned id, unique within Personnel',
            'IsUdf': false
        },
        {
            'Name': 'ObjectKey',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': false,
            'Type': 'ObjectKey',
            'IsEnum': false,
            'IsUdf': false
        },
        {
            'Name': 'OnWatchList',
            'LocalizedName': 'On Watchlist',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'Whether or not this person is on the watchlist.',
            'IsUdf': false
        },
        {
            'Name': 'Operator',
            'LocalizedName': 'Operator',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': false,
            'IsPersistent': false,
            'Type': 'ObjectKey',
            'IsEnum': false,
            'Description': 'Operator associated with this personnel record',
            'LinkedProperties': [
                'OperatorID'
            ],
            'LookupData': {
                'IsQueryable': true,
                'PersistentTypeProperty': '',
                'PersistentIdProperty': 'OperatorID',
                'TargetName': 'Name',
                'TargetObjectID': 'ObjectID',
                'ValidLookupTypes': [
                    'SoftwareHouse.CrossFire.Common.Objects.Operator'
                ]
            },
            'IsUdf': false
        },
        {
            'Name': 'OperatorID',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'MinValue': 1.0,
            'MaxValue': 2147483647.0,
            'Description': 'Default tooltip text for property OperatorID.',
            'IsUdf': false
        },
        {
            'Name': 'PartitionID',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'MinValue': 1.0,
            'MaxValue': 2147483647.0,
            'Description': 'PartitionID',
            'IsUdf': false
        },
        {
            'Name': 'PartitionKey',
            'LocalizedName': 'Partition Name',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': false,
            'Type': 'ObjectKey',
            'IsEnum': false,
            'Description': 'Partition of object',
            'LinkedProperties': [
                'PartitionID'
            ],
            'LookupData': {
                'IsQueryable': true,
                'PersistentTypeProperty': '',
                'PersistentIdProperty': 'PartitionID',
                'TargetName': 'Name',
                'TargetObjectID': 'ObjectID',
                'ValidLookupTypes': [
                    'SoftwareHouse.CrossFire.Common.Objects.Partition'
                ]
            },
            'IsUdf': false
        },
        {
            'Name': 'PersonnelType',
            'LocalizedName': 'Personnel Type',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': false,
            'IsPersistent': false,
            'Type': 'ObjectKey',
            'IsEnum': false,
            'Description': 'Select a Personnel Type for this personnel record.',
            'LinkedProperties': [
                'PersonnelTypeID'
            ],
            'LookupData': {
                'IsQueryable': true,
                'PersistentTypeProperty': '',
                'PersistentIdProperty': 'PersonnelTypeID',
                'TargetName': 'Name',
                'TargetObjectID': 'ObjectID',
                'ValidLookupTypes': [
                    'SoftwareHouse.NextGen.Common.SecurityObjects.PersonnelType'
                ]
            },
            'IsUdf': false
        },
        {
            'Name': 'PersonnelTypeID',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'MinValue': 0.0,
            'MaxValue': 2147483647.0,
            'Description': 'Default tooltip text for property PersonnelTypeID.',
            'IsUdf': false
        },
        {
            'Name': 'PIN',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'MinValue': 0.0,
            'MaxValue': 2147483647.0,
            'Description': 'PIN (Personal Identification Number) is a number assigned to a cardholder. The cardholder uses this PIN at keypads when required. The maximum number is specified in System Variables.',
            'IsUdf': false
        },
        {
            'Name': 'PrimaryPortrait',
            'LocalizedName': 'Primary Portrait',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': true,
            'Type': 'Binary',
            'IsEnum': false,
            'Description': 'The primary portrait for this personnel record.',
            'DynamicViewColumnType': 'Image',
            'IsUdf': false
        },
        {
            'Name': 'Protected',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'Whether this personnel record is protected from deletion in the database or not.',
            'IsUdf': false
        },
        {
            'Name': 'RegisterWithCloud',
            'LocalizedName': 'Register With Cloud',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'Check to register this person with the CCure Go Access Cloud',
            'IsUdf': false
        },
        {
            'Name': 'Salt',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': true,
            'Type': 'Binary',
            'IsEnum': false,
            'IsUdf': false
        },
        {
            'Name': 'Signature',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': true,
            'Type': 'Binary',
            'IsEnum': false,
            'IsUdf': false
        },
        {
            'Name': 'StolenCredentials',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'MinValue': 0.0,
            'MaxValue': 9223372036854775807.0,
            'Description': 'The number of stolen credentials for this person.',
            'IsUdf': false
        },
        {
            'Name': 'SupervisorOption',
            'LocalizedName': 'Supervision Option',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'SoftwareHouse.NextGen.Common.SecurityObjectDefinitions.PersonnelSupervisionType',
            'IsEnum': true,
            'Description': 'Select an option if person is a Supervisor or Supervised Person (Supervisee).',
            'IsUdf': false
        },
        {
            'Name': 'Template',
            'LocalizedName': 'Template',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'Whether this personnel record can be used as template or not.',
            'IsUdf': false
        },
        {
            'Name': 'TemplateID',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'MinValue': 0.0,
            'MaxValue': 2147483647.0,
            'Description': 'Default tooltip text for property TemplateID.',
            'IsUdf': false
        },
        {
            'Name': 'Temporary',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': true,
            'Type': 'Boolean',
            'IsEnum': false,
            'Description': 'Default tooltip text for property Temporary.',
            'IsUdf': false
        },
        {
            'Name': 'Text1',
            'LocalizedName': 'Text1',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 150,
            'Description': 'Customer Field: Enter up to 150 alpha numeric characters',
            'IsUdf': false
        },
        {
            'Name': 'Text10',
            'LocalizedName': 'Text10',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 150,
            'Description': 'Customer Field: Enter up to 150 alpha numeric characters',
            'IsUdf': false
        },
        {
            'Name': 'Text11',
            'LocalizedName': 'Text11',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 150,
            'Description': 'Customer Field: Enter up to 150 alpha numeric characters',
            'IsUdf': false
        },
        {
            'Name': 'Text12',
            'LocalizedName': 'Text12',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 150,
            'Description': 'Customer Field: Enter up to 150 alpha numeric characters.  Must be unique.',
            'IsUdf': false
        },
        {
            'Name': 'Text13',
            'LocalizedName': 'Text13',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 150,
            'Description': 'Customer Field: Enter up to 150 alpha numeric characters. Must be unique.',
            'IsUdf': false
        },
        {
            'Name': 'Text14',
            'LocalizedName': 'Text14',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 150,
            'Description': 'Customer Field: Enter up to 150 alpha numeric characters',
            'IsUdf': false
        },
        {
            'Name': 'Text15',
            'LocalizedName': 'Text15',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 150,
            'Description': 'Customer Field: Enter up to 150 alpha numeric characters',
            'IsUdf': false
        },
        {
            'Name': 'Text16',
            'LocalizedName': 'Text16',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 150,
            'Description': 'Customer Field: Enter up to 150 alpha numeric characters',
            'IsUdf': false
        },
        {
            'Name': 'Text17',
            'LocalizedName': 'Text17',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 150,
            'Description': 'Customer Field: Enter up to 150 alpha numeric characters',
            'IsUdf': false
        },
        {
            'Name': 'Text18',
            'LocalizedName': 'Text18',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 150,
            'Description': 'Customer Field: Enter up to 150 alpha numeric characters',
            'IsUdf': false
        },
        {
            'Name': 'Text19',
            'LocalizedName': 'Text19',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 150,
            'Description': 'Customer Field: Enter up to 150 alpha numeric characters',
            'IsUdf': false
        },
        {
            'Name': 'Text2',
            'LocalizedName': 'Text2',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 150,
            'Description': 'Customer Field: Enter up to 150 alpha numeric characters',
            'IsUdf': false
        },
        {
            'Name': 'Text20',
            'LocalizedName': 'Text20',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 150,
            'Description': 'Customer Field: Enter up to 150 alpha numeric characters',
            'IsUdf': false
        },
        {
            'Name': 'Text21',
            'LocalizedName': 'Text21',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 150,
            'Description': 'Customer Field: Enter up to 150 alpha numeric characters',
            'IsUdf': false
        },
        {
            'Name': 'Text22',
            'LocalizedName': 'Text22',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 150,
            'Description': 'Customer Field: Enter up to 150 alpha numeric characters',
            'IsUdf': false
        },
        {
            'Name': 'Text23',
            'LocalizedName': 'Text23',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 150,
            'Description': 'Customer Field: Enter up to 150 alpha numeric characters',
            'IsUdf': false
        },
        {
            'Name': 'Text24',
            'LocalizedName': 'Text24',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 150,
            'Description': 'Customer Field: Enter up to 150 alpha numeric characters',
            'IsUdf': false
        },
        {
            'Name': 'Text25',
            'LocalizedName': 'Text25',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 150,
            'Description': 'Customer Field: Enter up to 150 alpha numeric characters',
            'IsUdf': false
        },
        {
            'Name': 'Text3',
            'LocalizedName': 'Text3',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 150,
            'Description': 'Customer Field: Enter up to 150 alpha numeric characters',
            'IsUdf': false
        },
        {
            'Name': 'Text4',
            'LocalizedName': 'Text4',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 150,
            'Description': 'Customer Field: Enter up to 150 alpha numeric characters',
            'IsUdf': false
        },
        {
            'Name': 'Text5',
            'LocalizedName': 'Text5',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 150,
            'Description': 'Customer Field: Enter up to 150 alpha numeric characters',
            'IsUdf': false
        },
        {
            'Name': 'Text6',
            'LocalizedName': 'Text6',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 150,
            'Description': 'Customer Field: Enter up to 150 alpha numeric characters',
            'IsUdf': false
        },
        {
            'Name': 'Text7',
            'LocalizedName': 'Text7',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 150,
            'Description': 'Customer Field: Enter up to 150 alpha numeric characters',
            'IsUdf': false
        },
        {
            'Name': 'Text8',
            'LocalizedName': 'Text8',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 150,
            'Description': 'Customer Field: Enter up to 150 alpha numeric characters',
            'IsUdf': false
        },
        {
            'Name': 'Text9',
            'LocalizedName': 'Text9',
            'IsUserSelectable': true,
            'IsReadOnly': false,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 150,
            'Description': 'Customer Field: Enter up to 150 alpha numeric characters',
            'IsUdf': false
        },
        {
            'Name': 'TransactionCount',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': false,
            'IsPersistent': true,
            'Type': 'Int32',
            'IsEnum': false,
            'MinValue': 0.0,
            'MaxValue': 9223372036854775807.0,
            'Description': 'Enter a number between 0 and 9223372036854775807',
            'IsUdf': false
        },
        {
            'Name': 'TwoFactorUserID',
            'IsUserSelectable': false,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': -1,
            'IsUdf': false
        },
        {
            'Name': 'WindowsPrincipal',
            'LocalizedName': 'Windows Principal',
            'IsUserSelectable': true,
            'IsReadOnly': true,
            'IsSearchable': true,
            'IsPersistent': true,
            'Type': 'String',
            'IsEnum': false,
            'MaxSize': 100,
            'Description': 'Enter the Windows Principal Name ( DOMAIN\\USERNAME)',
            'IsUdf': false
        }
    ]
};

export { typeName, schema };